DataGerry/DataGerry

app/src/app/framework/category/category.module.ts
app/src/app/framework/category/components/modals/add-category-modal/add-category-modal.component.html
app/src/app/framework/category/components/modals/add-category-modal/add-category-modal.component.ts
app/src/app/framework/models/cmdb-type.ts
app/src/app/framework/services/category.service.ts
app/src/app/framework/type/builder/builder.module.ts
app/src/app/framework/type/type-builder/type-basic-step/type-basic-step.component.html
app/src/app/framework/type/type-builder/type-basic-step/type-basic-step.component.ts
app/src/app/framework/type/type-builder/type-builder.component.ts
app/src/app/framework/type/type.module.ts
app/src/app/services/api-call.service.ts
cmdb/framework/cmdb_category.py
cmdb/interface/rest_api/framework_routes/category_routes.py

Starting from the last commit, I re-added the Quick-Add feature from before [[NET-331][NET-401] Make current order](https://github.com/NETHINKS/DATAGERRY/commit/cd10a83e4eae7419b7d70e8e939ece7b5a6a9b35) and updated it to the new category scheme.
[NET-331]: https://nethinks.atlassian.net/browse/NET-331
[NET-401]: https://nethinks.atlassian.net/browse/NET-401

[NET-331][NET-401] Fix/Readd the quick add button

---

app/src/app/settings/exportd-job-settings/exportd-job-settings-builder/exportd-job-sources-step/exportd-job-sources-step.component.ts

See [[NET-448]](https://nethinks.atlassian.net/browse/NET-448) for details.
Fixed by using the find method on component layer.
Also did a little bit of cleanup.
[NET-448]: https://nethinks.atlassian.net/browse/NET-448

[NET-448] Exportd UI: Condition dropdown in sources step not updated properly

---

cmdb/interface/rest_api/__init__.py
cmdb/interface/rest_api/settings_routes/system_routes.py
requirements.txt

Bug report: https://nethinks.atlassian.net/browse/NET-553
Fixed with: https://nethinks.atlassian.net/browse/NET-554

[NET-553][NET-554] Bugfix flask caching unused

---

requirements.txt

Bug report: https://nethinks.atlassian.net/browse/NET-550
Fixed with: https://nethinks.atlassian.net/browse/NET-551

[NET-550][NET-551] Update gunicorn to 20.0.4

---

cmdb/interface/config.py
cmdb/interface/docs/__init__.py
cmdb/interface/gunicorn.py
cmdb/interface/net_app/__init__.py
cmdb/interface/rest_api/__init__.py
cmdb/utils/logger.py

Bug report: https://nethinks.atlassian.net/browse/NET-550
Fixed in: Bug report: https://nethinks.atlassian.net/browse/NET-551

[NET-551] Fix gunicorn logging output to stdout and stderr

---

app/src/app/framework/type/type.component.html
app/src/app/framework/type/type.component.ts

Bug report: https://nethinks.atlassian.net/browse/NET-571

[NET-571] Missing type table functions

---

app/src/app/export/export.service.ts
app/src/app/framework/object/object-list-by-type/object-list-by-type.component.ts
app/src/app/framework/object/object-view/object-footer/object-reference-list/object-reference-list.component.html
app/src/app/framework/object/object-view/object-footer/object-reference-list/object-reference-list.component.ts
app/src/app/layout/components/table/table.component.ts
cmdb/file_export/export_types.py
cmdb/file_export/file_exporter.py
cmdb/interface/rest_api/exporter_routes/file_routes.py

Built export functionality for objects in the "Referenced By" tab in the object view page.
The objects are sorted by type and stored in one file for each type, which are then zipped and exported as .zip file.

[NET-477] Feature referenced object export

---

cmdb/exportd/externals/external_systems.py
docs/source/admin_guide/exportd.rst
requirements.txt

https://nethinks.atlassian.net/browse/NET-364

[NET-364] Feature exportd plugin mariadb

---

cmdb/security/auth/__init__.py
cmdb/security/auth/providers/internal_providers.py

[NET-612](https://nethinks.atlassian.net/browse/NET-612)

[NET-612] No authentication config possible

---

app/src/app/framework/object/object-bulk-change/object-bulk-change.component.ts
app/src/app/framework/services/object.service.ts

[[NET-624] Bulk changes can not be applied](https://nethinks.atlassian.net/browse/NET-624)
[NET-624]: https://nethinks.atlassian.net/browse/NET-624

[NET-624] Passing parameters in the HTTP packet.

---

app/src/app/app.component.ts
app/src/app/framework/services/type.service.ts

Fixes bug referenced in [NET-620](https://nethinks.atlassian.net/browse/NET-620)

[NET-620] create type ref fix

---

app/src/app/framework/render/fields/text/password.component.html
app/src/app/framework/render/fields/text/password.component.ts
cmdb/security/auth/providers/external_providers.py

[NET-579](https://nethinks.atlassian.net/browse/NET-579)

[NET-579] LDAP password hidden

---

cmdb/interface/rest_api/exporter_routes/export_type_routes.py

Fixes the issue referenced in [NET-619](https://nethinks.atlassian.net/browse/NET-619)

[NET-619] fixed json export

---

app/src/app/import/import-objects/type-mapping/csv-mapping/csv-mapping.component.ts
cmdb/importer/improve_object.py

Resolves the issue mentioned in [NET-576](https://nethinks.atlassian.net/browse/NET-576)

[NET-576] changed function with which to compare property entries

---

app/src/app/framework/type/type.component.ts

[NET-621](https://nethinks.atlassian.net/browse/NET-621)

[NET-621] Remove wrong header target cell

---

cmdb/__setup__.py
cmdb/user_management/models/group.py
cmdb/user_management/models/user.py

[NET-641](https://nethinks.atlassian.net/browse/NET-641)

[NET-641] Fix user management insert convertion

---

app/src/app/framework/object/components/object-actions/object-actions.component.ts
app/src/app/framework/object/object-add/object-add.component.ts
app/src/app/framework/object/object-copy/object-copy.component.ts
app/src/app/framework/object/object-list-by-type/object-list-by-type.component.ts
app/src/app/layout/components/table/table.component.ts
app/src/app/layout/services/sidebar.service.ts
app/src/app/layout/structure/sidebar/sidebar-type.component.ts

Updates the object counter in the category sidebar when objects are added or deleted.
Resolves the issue stated in [NET-468](https://nethinks.atlassian.net/browse/NET-468)

[NET-468] Feature object counter in category sidebar

---

cmdb/security/auth/providers/external_providers.py

[NET-623](https://nethinks.atlassian.net/browse/NET-623)

[NET-650] Add length validation for ldap connection entries

---

app/src/app/framework/models/cmdb-render.ts
app/src/app/framework/models/cmdb-type.ts
app/src/app/framework/services/object.service.ts
app/src/app/framework/type/builder/builder.module.ts
app/src/app/framework/type/components/clean-button/clean-button.component.html
app/src/app/framework/type/components/clean-button/clean-button.component.ts
app/src/app/framework/type/modals/cleanup-modal/cleanup-modal.component.html
app/src/app/framework/type/modals/cleanup-modal/cleanup-modal.component.ts
app/src/app/framework/type/type.component.html
app/src/app/framework/type/type.component.ts
app/src/app/framework/type/type.module.ts
app/src/app/layout/structure/navigation/navigation.component.html
cmdb/framework/cmdb_object.py
cmdb/framework/cmdb_render.py
cmdb/framework/managers/framework_manager.py
cmdb/framework/managers/type_manager.py
cmdb/framework/models/type.py
cmdb/framework/results/list.py
cmdb/interface/response.py
cmdb/interface/rest_api/framework_routes/object_routes.py
cmdb/interface/rest_api/importer_routes/importer_type_routes.py
docs/source/api/rest/framework.rst

[NET-623](https://nethinks.atlassian.net/browse/NET-623)

[NET-623] Bugfix type cleanup button

---

app/src/app/framework/category/category-edit/category-edit.component.ts
app/src/app/framework/category/category-form/category-form.component.html
app/src/app/framework/category/category-form/category-form.component.ts
app/src/app/framework/services/type.service.ts
app/src/app/services/api-call.service.ts

[NET-644 : New categories have assigned types](https://nethinks.atlassian.net/browse/NET-644)

[NET-644] Get assigned types for categories.

---

app/src/app/framework/type/builder/configs/edits/ref-field-edit.component.ts

Fixes issue mentioned in [NET-532](https://nethinks.atlassian.net/browse/NET-632)

[NET-632] fixed reference types not showing

---

app/src/app/framework/category/category-add/category-add.component.ts
app/src/app/framework/category/category-edit/category-edit.component.ts
app/src/app/framework/category/category.component.html
app/src/app/framework/category/category.component.ts
app/src/app/framework/type/type-builder/type-basic-step/type-basic-step.component.ts
app/src/app/framework/type/type-builder/type-builder.component.ts
app/src/app/layout/services/sidebar.service.ts
app/src/app/layout/structure/sidebar/sidebar.component.ts

[[NET-581] Left navigation bar empty after some logins](https://nethinks.atlassian.net/browse/NET-581)
[NET-581]: https://nethinks.atlassian.net/browse/NET-581

[NET-581] Load category tree for sidebar after login.

---

app/src/app/search/models/search-result.ts
app/src/app/search/search-bar/search-bar.component.html
app/src/app/search/search-bar/search-bar.component.ts
app/src/app/search/search.service.ts
cmdb/interface/rest_api/search_routes.py

[[NET-631] - Search option for active/inactive objects](https://nethinks.atlassian.net/browse/NET-631)
[NET-631]: https://nethinks.atlassian.net/browse/NET-631

[NET-631] Display number of search results(active/inactive).

---

app/src/app/framework/category/category-form/category-form.component.html
app/src/app/framework/category/category-form/category-form.component.ts

Fixes the issue mentioned in [NET-661](https://nethinks.atlassian.net/browse/NET-661)

[NET-661] Replaced reset button with cancel button

---

cmdb/importer/importer_object.py

Fixes the issue mentioned in [NET-311](https://nethinks.atlassian.net/browse/NET-311)

[NET-311] check if map element is not none instead of just the element

---

cmdb/interface/rest_api/importer_routes/importer_object_routes.py

Fixes the issue mentioned in [NET-660](https://nethinks.atlassian.net/browse/NET-660)

[NET-660][Bugfix] file importer logs

---

app/src/app/framework/services/category.service.ts
app/src/app/framework/services/type.service.ts
app/src/app/search/search-bar/search-bar-tag/search-bar-tag-icon.component.html
app/src/app/search/search-bar/search-bar.component.html
app/src/app/search/search-bar/search-bar.component.ts
app/src/app/search/search-result/search-result-bar/search-result-bar.component.ts
app/src/app/services/validator.service.ts
cmdb/search/params.py
cmdb/search/query/pipe_builder.py

[[NET-651] Make regex in search optional](https://nethinks.atlassian.net/browse/NET-651)
[NET-651]: https://nethinks.atlassian.net/browse/NET-651

[NET-651] Make regex in search optional.

---

cmdb/interface/rest_api/settings_routes/system_routes.py

Fixes the issue mentioned in NET-673

[NET-673] allow access to DATAGERRY version for all users

---

app/src/app/services/request-cache.service.ts

[NET-675](https://nethinks.atlassian.net/browse/NET-675)

[NET-675] Remove cache debug message

---

app/src/app/framework/object/object-routing.module.ts
app/src/app/framework/object/object-view/object-view.component.html
app/src/app/framework/object/object-view/object-view.component.ts
app/src/app/framework/object/objects-by-type/objects-by-type.component.ts
app/src/app/framework/resolvers/object-view-resolver.service.ts
app/src/app/framework/services/object.service.ts

[[NET-672] Problems when logging out from the object view page](https://nethinks.atlassian.net/browse/NET-672)
[NET-672]: https://nethinks.atlassian.net/browse/NET-672

[NET-672] routeReuseStrategy replaced by resolve.

---

app/src/app/framework/object/objects-by-type/objects-by-type.component.html
app/src/app/framework/object/objects-by-type/objects-by-type.component.ts
app/src/app/layout/table/components/table-states/table-state.component.ts
app/src/app/layout/table/table.component.ts

[NET-671](https://nethinks.atlassian.net/browse/NET-671)

[NET-671] Add column visibility reset

---

app/src/app/import/import-objects/import-objects.component.ts
app/src/app/import/import-objects/type-mapping/type-mapping.component.ts

[[NET-677] Automatic field mapping in CSV importer.](https://nethinks.atlassian.net/browse/NET-677)
[NET-677]: https://nethinks.atlassian.net/browse/NET-677

[NET-677] Automatic field mapping in CSV importer.

---

app/src/app/management/users/components/user-form/user-form.component.html
app/src/app/management/users/components/user-form/user-form.component.scss
app/src/app/management/users/components/user-form/user-form.component.ts

[NET-679](https://nethinks.atlassian.net/browse/NET-679)

[NET-679] Inserted a remove button for the profile picture

---

app/src/app/management/services/user.service.ts

[NET-668](https://nethinks.atlassian.net/browse/NET-668)

[NET-668] user count

---

app/src/app/dashboard/dashboard.component.ts
app/src/app/framework/object/objects-by-type/objects-by-type.component.html
app/src/app/framework/object/objects-by-type/objects-by-type.component.ts
app/src/app/framework/render/simple/special/ref-simple.component.html
app/src/app/framework/render/simple/special/ref-simple.component.ts
app/src/app/layout/table/components/table-page-size/table-page-size.component.ts
cmdb/framework/cmdb_render.py
cmdb/interface/rest_api/framework_routes/object_routes.py
cmdb/user_management/models/user.py

[NET-699](https://nethinks.atlassian.net/browse/NET-699)

[NET-699] Feature implement smarter table render

---

app/src/app/framework/services/object.service.ts
cmdb/interface/rest_api/framework_routes/object_routes.py

[NET-701] Reference fields as summary fields caused issues on object view page
[NET-701]: https://nethinks.atlassian.net/browse/NET-701

[NET-701] Reference fields as summary fields caused issues on object view page

---

app/src/app/dashboard/dashboard.component.ts
app/src/app/framework/object/objects-by-type/objects-by-type.component.html
app/src/app/framework/object/objects-by-type/objects-by-type.component.ts
cmdb/interface/response.py

[NET-702](https://nethinks.atlassian.net/browse/NET-702)

[NET-702] Bugfix date encoding error tables

---

app/src/app/search/search-bar/search-bar.component.ts

[NET-704](https://nethinks.atlassian.net/browse/NET-704)

[NET-704] Fix auto setting of url parameters to search bar entries

---

app/src/app/framework/object/objects-by-type/objects-by-type.component.html
app/src/app/framework/object/objects-by-type/objects-by-type.component.ts
cmdb/__setup__.py
cmdb/interface/response.py
cmdb/interface/rest_api/user_management_routes/user_routes.py
cmdb/interface/route_utils.py
cmdb/security/auth/providers/external_providers.py
cmdb/user_management/models/user.py

[NET-706](https://nethinks.atlassian.net/browse/NET-706)

[NET-706] Bugfix date display error

---

app/src/app/layout/components/file-explorer/service/file.service.ts
cmdb/interface/rest_api/media_library_routes/media_file_routes.py

[[NET-711] Error output when creating folder in media library](https://nethinks.atlassian.net/browse/NET-711)
[NET-711]: https://nethinks.atlassian.net/browse/NET-711

[NET-711] Removed error-output from frontend console.

---

app/src/app/layout/structure/navigation/navigation.component.html

[NET-710] Switch feedback and profile button in menu
[NET-710]: https://nethinks.atlassian.net/browse/NET-710

[NET-710] Switch feedback and profile button in menu

---

cmdb/user_management/models/user.py
requirements.txt

[NET-714](https://nethinks.atlassian.net/browse/NET-714)

[NET-714] Add validation parser on user

---

app/src/app/framework/type/type-builder/type-builder.component.ts

[NET-715](https://nethinks.atlassian.net/browse/NET-715)

[NET-715] Fix selected category id compare in type builder

---

app/src/app/framework/type/type-builder/type-builder.component.ts

[NET-716](https://nethinks.atlassian.net/browse/NET-716)

[NET-716] Fix category update error on type builder

---

app/src/app/acl/acl.module.ts
app/src/app/acl/acl.types.ts
app/src/app/framework/models/cmdb-type.ts
app/src/app/framework/type/type-builder/type-acl-step/groups-acl-tabs/groups-acl-tabs.component.html
app/src/app/framework/type/type-builder/type-acl-step/groups-acl-tabs/groups-acl-tabs.component.scss
app/src/app/framework/type/type-builder/type-acl-step/groups-acl-tabs/groups-acl-tabs.component.ts
app/src/app/framework/type/type-builder/type-acl-step/type-acl-step.component.html
app/src/app/framework/type/type-builder/type-acl-step/type-acl-step.component.ts
app/src/app/framework/type/type-builder/type-builder.component.html
app/src/app/framework/type/type-builder/type-builder.component.ts
app/src/app/framework/type/type.module.ts
app/src/app/layout/components/block/block.component.html
app/src/app/layout/components/block/block.component.scss
app/src/app/layout/components/block/block.component.ts
app/src/app/layout/layout.module.ts
cmdb/framework/models/type.py
cmdb/security/access_control/__init__.py

[NET-681](https://nethinks.atlassian.net/browse/NET-681)

[NET-681] Change type model for new object ACLs

---

app/src/app/framework/services/object.service.ts
cmdb/framework/cmdb_object_manager.py
cmdb/framework/managers/category_manager.py
cmdb/framework/managers/framework_manager.py
cmdb/framework/managers/object_manager.py
cmdb/framework/models/type.py
cmdb/interface/rest_api/framework_routes/object_routes.py
cmdb/interface/route_utils.py
cmdb/search/query/builder.py
cmdb/search/query/pipe_builder.py
cmdb/search/searchers.py
cmdb/security/acl/__init__.py
cmdb/security/acl/builder.py
cmdb/security/acl/control.py
cmdb/security/acl/errors.py
cmdb/security/acl/permission.py
cmdb/security/acl/sections.py

[NET-682](https://nethinks.atlassian.net/browse/NET-682)

[NET-682] Enforce acl object crud

---

app/src/app/framework/render/render-element/render-element.component.ts

[[NET-728] Data not refreshed when switching between object view pages](https://nethinks.atlassian.net/browse/NET-728)
[NET-728]: https://nethinks.atlassian.net/browse/NET-728

[NET-728] Remove/Update formcontrols if already exist.

---

cmdb/file_export/export_types.py

[NET-732] Fixed field mapping in XLSX exporter
[NET-732]: https://nethinks.atlassian.net/browse/NET-732

[NET-732] Fixed field mapping in XLSX exporter

---

cmdb/file_export/export_types.py

[NET-733] File Exporter does not honor type definition
[NET-733]: https://nethinks.atlassian.net/browse/NET-733

[NET-733] File Exporter does not honor type definition

---

app/src/app/framework/object/object-bulk-change/object-bulk-change-editor/object-bulk-change-editor.component.html
app/src/app/framework/object/object-bulk-change/object-bulk-change-editor/object-bulk-change-editor.component.ts
app/src/app/framework/object/object-bulk-change/object-bulk-change-preview/object-bulk-change-preview.component.html
app/src/app/framework/object/object-bulk-change/object-bulk-change-preview/object-bulk-change-preview.component.ts
app/src/app/framework/object/object-bulk-change/object-bulk-change.component.html
app/src/app/framework/object/object-bulk-change/object-bulk-change.component.ts
app/src/app/framework/object/objects-by-type/objects-by-type.component.html
app/src/app/framework/object/objects-by-type/objects-by-type.component.ts
app/src/app/framework/render/components/object-bulk-input-appends/object-bulk-input-appends.component.html
app/src/app/framework/render/components/object-bulk-input-appends/object-bulk-input-appends.component.ts
app/src/app/framework/render/fields/choice/checkbox.component.html
app/src/app/framework/render/fields/choice/radio.component.html
app/src/app/framework/render/fields/choice/select.component.html
app/src/app/framework/render/fields/components.fields.ts
app/src/app/framework/render/fields/date/date.component.html
app/src/app/framework/render/fields/math/number.component.html
app/src/app/framework/render/fields/special/ref.component.html
app/src/app/framework/render/fields/special/ref.component.ts
app/src/app/framework/render/fields/text/password.component.html
app/src/app/framework/render/fields/text/text.component.html
app/src/app/framework/render/fields/textarea/textarea.component.html
app/src/app/framework/render/render-element/render-element.component.ts
app/src/app/framework/render/render.component.html
app/src/app/framework/render/render.component.ts
app/src/app/framework/render/simple/special/ref-simple.component.html
app/src/app/framework/render/simple/special/ref-simple.component.ts
cmdb/framework/cmdb_render.py
cmdb/interface/rest_api/framework_routes/object_routes.py

[NET-712](https://nethinks.atlassian.net/browse/NET-712 ) Bulk Change preview does not show chosen references correctly

[NET-712] Bugfix bulk preview show references

---

app/src/app/auth/directives/permission-link.directive.ts
app/src/app/auth/services/acl-permission.service.ts
app/src/app/dashboard/dashboard.component.html
app/src/app/framework/models/cmdb-render.ts
app/src/app/framework/object/components/object-actions/object-actions.component.html
app/src/app/framework/object/components/object-actions/object-actions.component.ts
app/src/app/framework/object/components/object-table-actions/object-table-actions.component.html
app/src/app/framework/object/components/object-table-actions/object-table-actions.component.ts
app/src/app/framework/object/components/object-table-head/object-table-head.component.html
app/src/app/framework/object/components/object-table-head/object-table-head.component.ts
app/src/app/framework/object/object-view/object-view.component.html
app/src/app/framework/object/object-view/object-view.component.ts
app/src/app/framework/object/object.module.ts
app/src/app/framework/object/objects-by-type/objects-by-type.component.html
app/src/app/framework/object/objects-by-type/objects-by-type.component.ts
cmdb/framework/cmdb_render.py

[NET-689](https://nethinks.atlassian.net/browse/NET-689)

[NET-689] Restrict Button Access

---

cmdb/interface/rest_api/framework_routes/object_routes.py

[NET-748](https://nethinks.atlassian.net/browse/NET-748)

[NET-748] Table view: Error when deleting selected objects

---

cmdb/interface/rest_api/search_routes.py
cmdb/search/searchers.py

[[NET-683] Filter search results based on defined Object ACLs ](https://nethinks.atlassian.net/browse/NET-683)
[NET-683]: https://nethinks.atlassian.net/browse/NET-683

[NET-683] Search results based on acls

---

app/src/app/framework/object/components/object-table-head/object-table-head.component.html
app/src/app/framework/object/components/object-table-head/object-table-head.component.ts
app/src/app/framework/object/objects-by-type/objects-by-type.component.html
app/src/app/framework/object/objects-by-type/objects-by-type.component.ts

[NET-750](https://nethinks.atlassian.net/browse/NET-750)

[NET-750] Object type selection update

---

cmdb/interface/rest_api/framework_routes/object_routes.py

[NET-749](https://nethinks.atlassian.net/browse/NET-749)

[NET-749] Add ACLs to special routes

---

app/src/app/framework/type/type-builder/type-acl-step/groups-acl-tabs/groups-acl-tabs.component.html
app/src/app/framework/type/type-builder/type-acl-step/groups-acl-tabs/groups-acl-tabs.component.ts
app/src/app/framework/type/type-builder/type-acl-step/type-acl-step.component.html
app/src/app/framework/type/type-builder/type-acl-step/type-acl-step.component.ts
app/src/app/framework/type/type-builder/type-builder.component.html
app/src/app/framework/type/type-builder/type-builder.component.ts

[NET-756](https://nethinks.atlassian.net/browse/NET-756)

[NET-756] Disabled next step button when the next entry isn't empty

---

app/src/app/export/export-objects/export-objects.component.html
app/src/app/export/export-objects/export-objects.component.ts
app/src/app/export/export-objects/model/export-objects-file-extension.ts
app/src/app/export/export.service.ts
app/src/app/framework/object/components/object-table-head/object-table-head.component.html
app/src/app/framework/object/components/object-table-head/object-table-head.component.ts
app/src/app/framework/object/object-view/object-footer/object-reference-list/object-reference-list.component.html
app/src/app/framework/object/object-view/object-footer/object-reference-list/object-reference-list.component.ts
app/src/app/framework/object/objects-by-type/objects-by-type.component.ts
cmdb/file_export/export_types.py
cmdb/file_export/file_exporter.py
cmdb/interface/rest_api/exporter_routes/file_routes.py

[[NET-685] Enforce new Object ACLs for object  file exports](https://nethinks.atlassian.net/browse/NET-685)
[NET-685]: https://nethinks.atlassian.net/browse/NET-685

[NET-685] acls for object files exports

---

app/src/app/app.module.ts
app/src/app/framework/object/object-view/object-view.component.html
app/src/app/framework/render/fields/special/ref.component.html
app/src/app/framework/render/fields/special/ref.component.ts
app/src/app/framework/render/render-element/render-element.component.html
app/src/app/framework/render/render-element/render-element.component.ts
app/src/app/framework/render/simple/special/ref-simple.component.html
app/src/app/framework/render/simple/special/ref-simple.component.ts
cmdb/framework/cmdb_object_manager.py
cmdb/framework/cmdb_render.py
cmdb/interface/rest_api/framework_routes/object_routes.py

[NET-684](https://nethinks.atlassian.net/browse/NET-684)

[NET-684] Handle object reference acl

---

app/src/app/layout/components/feedback-form/feedback-form.component.html
app/src/app/layout/components/feedback-form/feedback-form.component.ts

[NET-763](https://nethinks.atlassian.net/browse/NET-763) User feedback email validator was not implemented

[NET-763] Implement email validation on user feedback form

---

app/package-lock.json
app/package.json
app/src/app/app.component.html
app/src/app/app.component.ts
app/src/app/app.module.ts
app/src/app/framework/category/components/modals/add-category-modal/add-category-modal.component.ts
app/src/app/framework/object/object.module.ts
app/src/app/import/import-objects/import-objects.component.ts
app/src/app/layout/layout.module.ts
app/src/app/layout/progress/progress-bar.service.ts
app/src/app/layout/progress/progress-bar/progress-bar.component.html
app/src/app/layout/progress/progress-bar/progress-bar.component.scss
app/src/app/layout/progress/progress-bar/progress-bar.component.ts
app/src/app/layout/progress/progress-bar/progress-bar.types.ts
app/src/app/layout/progress/progress-spinner.service.ts
app/src/app/layout/progress/progress-spinner/progress-spinner.component.html
app/src/app/layout/progress/progress-spinner/progress-spinner.component.scss
app/src/app/layout/progress/progress-spinner/progress-spinner.component.ts
app/src/app/layout/progress/progress-spinner/progress-spinner.types.ts
app/src/app/layout/progress/progress.module.ts
app/src/app/search/search.component.ts
app/src/app/search/search.module.ts
app/src/app/services/app-loading.service.ts
app/src/app/services/application-loading-indicator.service.ts
app/src/app/settings/auth-settings/auth-settings.component.ts

[NET-739](https://nethinks.atlassian.net/browse/NET-739)

[NET-739] Angular loading indicators

---

app/src/app/framework/services/type.service.ts

[[NET-761]](https://nethinks.atlassian.net/browse/NET-761)
[NET-761]: https://nethinks.atlassian.net/browse/NET-761

[NET-761] remove expression to ignore all white space characters.

---

app/src/app/dashboard/dashboard.component.html
app/src/app/dashboard/dashboard.component.ts

[[NET-757] ](https://nethinks.atlassian.net/browse/NET-757)
[NET-757]: https://nethinks.atlassian.net/browse/NET-757

[NET-757] Add delete action logic to dashboard table.

---

app/src/app/framework/render/fields/special/ref.component.ts

[[NET-758]](https://nethinks.atlassian.net/browse/NET-758)
[NET-758]: https://nethinks.atlassian.net/browse/NET-758

[NET-758] Added new conditions for protected references.

---

cmdb/framework/cmdb_object_manager.py
cmdb/interface/rest_api/framework_routes/object_link_routes.py

[[NET-688]](https://nethinks.atlassian.net/browse/NET-688)
[NET-688]: https://nethinks.atlassian.net/browse/NET-688

[NET-688] Backend: Check linked objects for acls.

---

app/src/app/dashboard/dashboard.component.ts

[NET-800](https://nethinks.atlassian.net/browse/NET-800)

[NET-800] Get categories for type chart with new API.

---

cmdb/importer/importer_base.py

[NET-799](https://nethinks.atlassian.net/browse/NET-799)

[NET-799] added check for Permissions in CSV Export

---

app/src/app/dashboard/dashboard.component.ts

[NET-800](https://nethinks.atlassian.net/browse/NET-800)

[NET-800] Implement missing OnDestroy.

---

app/src/app/auth/services/auth.service.ts
app/src/app/framework/render/simple/special/ref-simple.component.html
app/src/app/management/user-settings/services/user-settings.service.ts

[NET-802](https://nethinks.atlassian.net/browse/NET-802)

[NET-802] user is not updated

---

app/src/app/error/interceptors/http-error.interceptor.tx.ts
app/src/app/framework/object/modals/object-link-add-modal/object-link-add-modal.component.html
app/src/app/framework/object/modals/object-link-add-modal/object-link-add-modal.component.ts
app/src/app/framework/object/object-view/object-footer/object-links/object-links.component.html
app/src/app/framework/object/object-view/object-footer/object-links/object-links.component.ts
app/src/app/framework/services/link.service.ts
app/src/app/framework/services/object.service.ts
cmdb/framework/cmdb_link.py
cmdb/framework/cmdb_object_manager.py
cmdb/interface/rest_api/framework_routes/object_link_routes.py

[NET-688](https://nethinks.atlassian.net/browse/NET-688)

[NET-688] Enforce object links acl

---

app/src/app/framework/services/type.service.ts
app/src/app/framework/type/components/clean-button/clean-button.component.ts
app/src/app/framework/type/components/type-table-actions/type-table-actions.component.html
app/src/app/framework/type/components/type-table-actions/type-table-actions.component.ts
app/src/app/framework/type/type.component.html
app/src/app/framework/type/type.component.ts
app/src/app/framework/type/type.module.ts
app/src/app/layout/helpers/type-label/type-label.component.html
app/src/app/layout/helpers/type-label/type-label.component.ts
app/src/app/layout/table/body/table-cell/table-cell.component.ts
app/src/app/layout/table/table.types.ts
app/src/scss/_table.scss

[NET-767](https://nethinks.atlassian.net/browse/NET-767) Type datatables replacement

[NET-767] Replace type datatables

---

app/src/app/framework/category/category.component.html
app/src/app/framework/category/category.component.ts
app/src/app/framework/category/category.module.ts
app/src/app/framework/category/components/category-node/category-node.component.ts
app/src/app/framework/category/components/modals/delete-category-modal/delete-category-modal.component.ts

[NET-766](https://nethinks.atlassian.net/browse/NET-766)

[NET-766] Category datatables replacement

---

app/src/app/dashboard/dashboard.component.ts
app/src/app/framework/services/type.service.ts
cmdb/framework/cmdb_object_manager.py
cmdb/interface/rest_api/framework_routes/object_routes.py

[NET-801](https://nethinks.atlassian.net/browse/NET-801)

[NET-801] Added acls for dashboard charts.

---

app/src/app/framework/object/components/object-actions/object-actions.component.ts
app/src/app/framework/object/object-add/object-add.component.ts
app/src/app/framework/object/object-copy/object-copy.component.ts
app/src/app/framework/type/type-builder/type-builder.component.ts
app/src/app/framework/type/type-delete/type-delete.component.ts

[NET-820](https://nethinks.atlassian.net/browse/NET-820)

[NET-820] Implement some missing ui toasts

---

app/src/app/framework/services/type.service.ts
app/src/app/import/import-objects/type-mapping/type-mapping.component.ts
cmdb/framework/cmdb_object_manager.py
cmdb/importer/importer_base.py
cmdb/interface/rest_api/importer_routes/importer_object_routes.py
cmdb/interface/rest_api/importer_routes/importer_route_utils.py

[NET-686](https://nethinks.atlassian.net/browse/NET-686)

[NET-686] Added ACLs for object import.

---

app/src/app/framework/models/cmdb-log.ts
app/src/app/framework/object/object-view/object-footer/object-log-list/object-log-list.component.html
app/src/app/framework/object/object-view/object-footer/object-log-list/object-log-list.component.ts
app/src/app/framework/object/object.module.ts
app/src/app/framework/services/log.service.ts
app/src/app/services/api-call.service.ts
app/src/app/settings/log-settings/log-object-settings/activate-tab/activate-tab.component.html
app/src/app/settings/log-settings/log-object-settings/activate-tab/activate-tab.component.ts
app/src/app/settings/log-settings/log-object-settings/deactivate-tab/deactivate-tab.component.html
app/src/app/settings/log-settings/log-object-settings/deactivate-tab/deactivate-tab.component.ts
app/src/app/settings/log-settings/log-object-settings/delete-tab/delete-tab.component.html
app/src/app/settings/log-settings/log-object-settings/delete-tab/delete-tab.component.ts
app/src/app/settings/log-settings/log-object-settings/log-object-settings.component.html
app/src/app/settings/log-settings/log-object-settings/log-object-settings.component.ts
app/src/app/settings/log-settings/log-object-settings/log-object-table-actions/log-object-table-actions.component.html
app/src/app/settings/log-settings/log-object-settings/log-object-table-actions/log-object-table-actions.component.ts
app/src/app/settings/log-settings/log-settings.module.ts
cmdb/framework/cmdb_log.py
cmdb/framework/cmdb_log_manager.py
cmdb/interface/rest_api/__init__.py
cmdb/interface/rest_api/log_routes.py

[NET-778](https://nethinks.atlassian.net/browse/NET-778)

[NET-778] Replace object logs datatables

---

cmdb/utils/wraps.py

[NET-819](https://nethinks.atlassian.net/browse/NET-819)
With the advanced 'deprecated' - decorator you can specify a message which function / class should be called instead.  It is also more useful to help the developer diagnose the problem by specifying the source filename and line number.

[NET-819] Extend deprecated decorator.

---

app/src/app/search/search-bar/search-bar.component.html
app/src/app/search/search-bar/search-bar.component.ts
app/src/app/search/search.component.html
app/src/app/search/search.component.ts

[NET-653](https://nethinks.atlassian.net/browse/NET-653)

[NET-653] Improved Search for Public ID

---

Makefile
contrib/rpm/datagerry.spec
contrib/setup/setup.sh
contrib/tmpfiles.d/datagerry.conf

[NET-843] Application crash when running the binary for a few days on some systems
[NET-843]: https://nethinks.atlassian.net/browse/NET-843

[NET-843] Application crash when running the binary for a few days on some systems

---

app/src/app/import/import-objects/type-mapping/type-mapping.component.ts
etc/cmdb.conf

[NET-841](https://nethinks.atlassian.net/browse/NET-841)

[NET-841] fix broken csv mapping

---

app/src/app/management/groups/components/group-form/group-form-helper/group-form-helper/group-form-helper.component.html
app/src/app/management/groups/components/group-form/group-form-helper/group-form-helper/group-form-helper.component.scss
app/src/app/management/groups/components/group-form/group-form-helper/group-form-helper/group-form-helper.component.ts
app/src/app/management/groups/components/group-form/group-form.component.html
app/src/app/management/groups/groups.module.ts

[NET-363](https://nethinks.atlassian.net/browse/NET-363)

[NET-363] improve usability of user right settings

---

app/src/app/import/import-objects/import-complete/failed-import-table/failed-import-table.component.html
app/src/app/import/import-objects/import-complete/failed-import-table/failed-import-table.component.ts
app/src/app/import/import-objects/import-complete/import-complete.component.html
app/src/app/import/import.module.ts

[NET-789](https://nethinks.atlassian.net/browse/NET-789)

[NET-789] Import datatables replacement

---

cmdb/interface/rest_api/framework_routes/object_routes.py

[NET-834](https://nethinks.atlassian.net/browse/NET-834)

[NET-834] Added empty match query if active_only is disabled

---

app/src/app/framework/object/objects-by-type/objects-by-type.component.ts

[NET-863](https://nethinks.atlassian.net/browse/NET-863)

[NET-863] Page number doesnt reset

---

app/src/app/dashboard/dashboard.component.ts
app/src/app/management/services/user.service.ts

[NET-864](https://nethinks.atlassian.net/browse/NET-864)

[NET-864] group user counter

---

app/src/app/framework/object/object-bulk-change/object-bulk-change-editor/object-bulk-change-editor.component.html
app/src/app/framework/object/object-bulk-change/object-bulk-change-editor/object-bulk-change-editor.component.ts
app/src/app/framework/object/object-bulk-change/object-bulk-change-preview/object-bulk-change-preview.component.html
app/src/app/framework/object/object-bulk-change/object-bulk-change.component.ts

[NET-869](https://nethinks.atlassian.net/browse/NET-869)

[NET-869] Bulk changes: in-/active button trigger changes.

---

app/src/app/management/users/modals/users-passwd-modal/users-passwd-modal.component.ts
app/src/app/management/users/users.component.ts

[NET-867](https://nethinks.atlassian.net/browse/NET-867)

[NET-867] Change password fix

---

cmdb/interface/rest_api/framework_routes/object_routes.py

[NET-823](https://nethinks.atlassian.net/browse/NET-823)

[NET-823] Reference fields are now rendered when entered into logs

---

cmdb/user_management/__init__.py

[NET-876](https://nethinks.atlassian.net/browse/NET-876)

[NET-876] UserModel label replaced with User

---

app/src/app/framework/category/category.component.ts
app/src/app/framework/object/objects-by-type/objects-by-type.component.html
app/src/app/framework/services/category.service.ts
app/src/app/framework/type/type-builder/type-basic-step/type-basic-step.component.ts

[NET-873](https://nethinks.atlassian.net/browse/NET-873)

[NET-873] Objects wont load

---

Makefile

[NET-878](https://nethinks.atlassian.net/browse/NET-878)

[NET-878] Extend Makefile for exporter.

---

app/src/app/dashboard/dashboard.component.html
app/src/app/dashboard/dashboard.component.ts
app/src/app/framework/object/objects-by-type/objects-by-type.component.ts
app/src/app/framework/render/fields/special/ref.component.ts
app/src/app/framework/services/object.service.ts
app/src/app/framework/services/special.service.ts

[NET-879](https://nethinks.atlassian.net/browse/NET-879) Dashboard load crash with empty objects

[NET-879] Fix dashboard services to generic api call

---

app/src/app/framework/category/components/modals/add-category-modal/add-category-modal.component.ts
app/src/app/framework/type/type-builder/type-basic-step/type-basic-step.component.ts
cmdb/framework/models/type.py

[NET-880](https://nethinks.atlassian.net/browse/NET-880) Loading indicator won't disappear on category quick

[NET-880] Loading wont disappear

---

app/src/app/dashboard/dashboard.component.ts
app/src/app/framework/object/objects-by-type/objects-by-type.component.ts

[NET-881](https://nethinks.atlassian.net/browse/NET-881) Object table build up slowly on safari

[NET-881] Move table date pipe in object tables

---

contrib/setup/setup.sh

[NET-884](https://nethinks.atlassian.net/browse/NET-884)

[NET-884] Fix spelling error in setup script

---

app/src/app/search/search.component.ts

[[NET-888]](https://nethinks.atlassian.net/browse/NET-888)
[NET-888]: https://nethinks.atlassian.net/browse/NET-888

[NET-888] Reload pagination parameter on resolve search.

---

app/src/app/framework/object/components/object-references-table/object-references-table.component.html
app/src/app/framework/object/components/object-references-table/object-references-table.component.ts

[NET-887](https://nethinks.atlassian.net/browse/NET-887)

[NET-887] Inserted summary column in referenced by table

---

app/src/app/framework/services/object.service.ts

[NET-901](https://nethinks.atlassian.net/browse/NET-901)

[NET-901] Reverse object order of latest and newest objects

---

app/src/app/dashboard/dashboard.component.html
app/src/app/dashboard/dashboard.component.ts
app/src/app/framework/services/object.service.ts

[NET-900](https://nethinks.atlassian.net/browse/NET-900)

[NET-900] Dashboard now loads all objects and pagination is enabled

---

app/package-lock.json
app/package.json
app/src/app/layout/components/feedback-form/feedback-form.component.html

**Highlights**
- Tooltips and popovers can have custom clases via customClass option.
- Added new .navbar-nav-scroll class for scrolling expanded navbar contents on mobile devices.
- For improved accessibiliy, spinners now slow down when prefers-reduced-motion is enabled.
- v4.x docs are now built on Hugo for easier maintenance and backports from v5.x.
- Darkened background-color of .dropdown-item for improved hover state contrast, and ligthened the disabled .dropdown-item color.
- Improved alignment of form validation tooltips.
- File inputs no longer extend beyond their containers.
[more](https://github.com/twbs/bootstrap/releases/tag/v4.6.0)

[NET-795] Update bootstrap 4.6.2

---

cmdb/interface/api_parameters.py
cmdb/interface/api_project.py
cmdb/interface/blueprint.py
cmdb/interface/response.py
cmdb/interface/rest_api/user_management_routes/group_parameters.py

_No Jira ID_ - as this is an experimental branch which has not been assigned to any task. However, since I find it very handy and would drastically reduce our data size, this time it goes directly as a pull request.
**Function looks like this:**
You can pass a parameter `projection` with _GET-Multi Responses_ of the **NEW** Rest-API. If a field with parameter value `1` is passed there, only this field is returned. This can also be used over multiple fields. If the value `0` is passed, all fields except this one are returned. Nested objects can be called with a _dot_ notation.
This is based on the [projection system](https://docs.mongodb.com/manual/tutorial/project-fields-from-query-results/) of MongoDB.

Rest data projection

---

app/src/app/search/search.module.ts

[[NET-927]](https://nethinks.atlassian.net/browse/NET-927)
[NET-927]: https://nethinks.atlassian.net/browse/NET-927

[NET-927] Add JwPaginationModule to search.module.ts

---

app/src/app/framework/object/components/object-log-list/object-log-change-view/object-log-change-view.component.html

[[NET-942]](https://nethinks.atlassian.net/browse/NET-942)
[NET-942]: https://nethinks.atlassian.net/browse/NET-942

[NET-942] Separate iteration of the changes for log view.

---

app/src/app/framework/models/cmdb-type-reference.ts
app/src/app/framework/render/fields/special/ref.component.html
app/src/app/framework/render/fields/special/ref.component.ts
app/src/app/framework/render/simple/special/ref-simple.component.html
app/src/app/framework/render/simple/special/ref-simple.component.ts
app/src/app/framework/type/builder/builder.module.ts
app/src/app/framework/type/builder/configs/edits/ref-field-edit.component.html
app/src/app/framework/type/builder/configs/edits/ref-field-edit.component.ts
app/src/app/framework/type/builder/controls/controls.common.ts
cmdb/framework/cmdb_errors.py
cmdb/framework/cmdb_render.py
cmdb/framework/models/type.py

[[NET-909]](https://nethinks.atlassian.net/browse/NET-909)
[NET-909]: https://nethinks.atlassian.net/browse/NET-909

[NET-909] Dynamic reference summary functionality

---

app/src/app/app.module.ts
app/src/app/auth/auth.module.ts
app/src/app/auth/guards/auth.guard.ts
app/src/app/auth/modals/session-timeout-notification-modal/session-timeout-notification-modal.component.html
app/src/app/auth/modals/session-timeout-notification-modal/session-timeout-notification-modal.component.ts
app/src/app/auth/services/auth.service.ts
app/src/app/auth/services/session-timeout.service.ts
app/src/app/error/interceptors/http-error.interceptor.tx.ts
app/src/app/layout/structure/footer/footer.component.html
app/src/app/layout/structure/footer/footer.component.ts
app/src/app/layout/structure/navigation/navigation.component.ts
app/src/app/main/main.module.ts

[NET-894](https://nethinks.atlassian.net/browse/NET-894) Session timeout notification

[NET-894] Session timeout notification

---

app/src/app/layout/table/table.module.ts
app/src/app/search/search-result/search-result.component.html
app/src/app/search/search.component.html
app/src/app/search/search.component.ts
app/src/app/search/search.module.ts

[NET-902](https://nethinks.atlassian.net/browse/NET-902)  Search results displayed length

[NET-902] Results display length

---

cmdb/interface/rest_api/auth_routes.py

[NET-958](https://nethinks.atlassian.net/browse/NET-958)

[NET-958] Add database manager to tokengenerator in auth_routes

---

app/src/app/search/search.component.html
app/src/app/search/search.component.ts

[NET-895](https://nethinks.atlassian.net/browse/NET-895) Return to last search page

[NET-895] Last search page

---

app/src/app/dashboard/dashboard.component.ts
app/src/app/framework/object/components/object-actions/object-actions.component.html
app/src/app/framework/object/components/object-table-actions/object-table-actions.component.html
app/src/app/framework/object/components/object-table-head/object-table-head.component.html
app/src/app/framework/object/object-add/object-add.component.ts
app/src/app/framework/services/type.service.ts
app/src/app/framework/type/type.component.ts
app/src/app/layout/structure/sidebar/sidebar.component.ts
cmdb/framework/cmdb_object_manager.py
cmdb/framework/managers/object_manager.py
cmdb/interface/rest_api/framework_routes/object_routes.py
cmdb/interface/rest_api/framework_routes/type_routes.py
cmdb/interface/rest_api/importer_routes/importer_object_routes.py
cmdb/security/acl/errors.py

[[NET-825] ](https://nethinks.atlassian.net/browse/NET-825)
[NET-825]: https://nethinks.atlassian.net/browse/NET-825

[NET-825] Deactivation of types.

---

app/src/app/framework/services/type.service.ts
cmdb/interface/rest_api/framework_routes/type_parameters.py
cmdb/interface/rest_api/framework_routes/type_routes.py

[NET-968](https://nethinks.atlassian.net/browse/NET-968)

[NET-968] Fix type default native parameter error

---

requirements.txt

Secuirty alert based on:
https://github.com/advisories/GHSA-f4w8-cv6p-x6r5
https://github.com/advisories/GHSA-f5g8-5qq7-938w
https://github.com/advisories/GHSA-hf64-x4gq-p99h
https://github.com/advisories/GHSA-3wvg-mj6g-m9cv
https://github.com/advisories/GHSA-vqcj-wrf2-7v73
https://github.com/advisories/GHSA-95q3-8gr9-gm8w

Update pillow package to 8.1.2

---

app/src/app/framework/render/fields/choice/radio.component.html

[[NET-971]](https://nethinks.atlassian.net/browse/NET-971) 
[NET-971]: https://nethinks.atlassian.net/browse/NET-971

[NET-971] Selecting different radio fields.

---

cmdb/importer/importer_object.py

[[NET-973]](https://nethinks.atlassian.net/browse/NET-973)
[NET-973]: https://nethinks.atlassian.net/browse/NET-973

[NET-973] Only check values of type 'checkbox' for boolean

---

app/src/app/framework/object/components/object-table-head/object-table-head.component.html
cmdb/exporter/exporter_base.py

[[NET-972]](https://nethinks.atlassian.net/browse/NET-972)
[NET-972]: https://nethinks.atlassian.net/browse/NET-972

[NET-972] Export JSON containing passed data.

---

app/src/app/layout/pipes/date-formatter.pipe.ts

[[NET-975]](https://nethinks.atlassian.net/browse/NET-975)
[NET-975]: https://nethinks.atlassian.net/browse/NET-975

[NET-975] Strict mode Removed. Checked if dateformatter parameter is a date string

---

app/src/app/layout/structure/navigation/navigation.component.html

[[NET-977] ](https://nethinks.atlassian.net/browse/NET-977)

[NET-977] Search line set right-justified

---

cmdb/docapi/docapi_base.py
cmdb/interface/rest_api/importer_routes/importer_object_routes.py
cmdb/templates/template_data.py

[NET-981](https://nethinks.atlassian.net/browse/NET-981)

[NET-981] Fix doc api render error on downloading pdf file routes

---

app/src/app/management/rights/rights.component.html
app/src/app/management/rights/rights.component.ts

[NET-979](https://nethinks.atlassian.net/browse/NET-979)

[NET-979] Fix loading table items order error on right list

---

app/src/app/management/users/users.component.html

[NET-980](https://nethinks.atlassian.net/browse/NET-980)

[NET-980] Fix using the item instead of the data in users-list for date display

---

app/src/app/framework/object/components/object-references/object-references-by-type/object-references-by-type.component.html
app/src/app/framework/object/components/object-references/object-references-by-type/object-references-by-type.component.ts
app/src/app/framework/object/components/object-references/object-references-table/object-references-table.component.html
app/src/app/framework/object/components/object-references/object-references-table/object-references-table.component.ts
app/src/app/framework/object/components/object-references/object-references-type-column/object-references-type-column.component.html
app/src/app/framework/object/components/object-references/object-references-type-column/object-references-type-column.component.ts
app/src/app/framework/object/object.module.ts
cmdb/framework/managers/object_manager.py
cmdb/search/query/builder.py

[NET-957](https://nethinks.atlassian.net/browse/NET-957)

[NET-957] Reference display sections

---

app/src/app/framework/object/object-routing.module.ts
app/src/app/framework/object/object.component.html
app/src/app/framework/object/object.component.ts
app/src/app/framework/object/object.module.ts
cmdb/framework/managers/object_manager.py

[NET-986](https://nethinks.atlassian.net/browse/NET-986)

[NET-986] Complete objects list

---

app/src/app/framework/object/components/object-log-list/object-log-change-view/object-log-change-view.component.ts

[[NET-987] ](https://nethinks.atlassian.net/browse/NET-987)
[NET-987]: https://nethinks.atlassian.net/browse/NET-987

[NET-987] Nullpointer when displaying changes in the object log list 

---

cmdb/framework/cmdb_render.py

[NET-988](https://nethinks.atlassian.net/browse/NET-988)

[NET-988] Fix field not found error handling in object render

---

app/src/app/dashboard/dashboard.component.html

[NET-1001](https://nethinks.atlassian.net/browse/NET-1001)

[NET-1001] Center active column in dashboard tables

---

.github/dependabot.yml

Change dependabot.yml assignees to “johndgrey“
[NET-1010](https://nethinks.atlassian.net/browse/NET-1010)

[NET-1010] Update dependabot.yml

---

app/src/app/search/search-bar/search-bar-tag-settings-form/search-bar-tag-settings-form.component.ts
app/src/app/search/search-bar/search-bar-tag/search-bar-tag-icon.component.ts
app/src/app/search/search-bar/search-bar-tag/search-bar-tag.component.ts
app/src/app/search/search-result/search-result-bar/search-result-bar.component.html
app/src/app/search/search-result/search-result-bar/search-result-bar.component.ts
app/src/app/search/search.component.html
app/src/app/search/search.component.ts
cmdb/framework/cmdb_render.py
cmdb/interface/rest_api/search_routes.py
cmdb/search/search_result.py
cmdb/search/searchers.py

[[NET-954]](https://nethinks.atlassian.net/browse/NET-954)
[NET-954]: https://nethinks.atlassian.net/browse/NET-954

[NET-954] Searchable reference section

---

cmdb/importer/importer_base.py

[[NET-1004]](https://nethinks.atlassian.net/browse/NET-1004)
[NET-1004]: https://nethinks.atlassian.net/browse/NET-1004

[NET-1004] Set correct timestamp for last-edit.

---

app/src/app/exportd/exportd-job-settings-builder/exportd-job-scheduling-step/exportd-job-scheduling-step.component.html
app/src/app/exportd/exportd-job-settings-builder/exportd-job-scheduling-step/exportd-job-scheduling-step.component.ts
cmdb/exportd/exportd_job/exportd_job.py
cmdb/exportd/exportd_job/exportd_job_manager.py
cmdb/exportd/exporter_base.py
cmdb/exportd/externals/external_systems.py
cmdb/exportd/service.py
cmdb/framework/cmdb_object_manager.py
cmdb/interface/rest_api/exportd_routes/exportd_job_routes.py
cmdb/templates/template_data.py

[[NET-974 ]](https://nethinks.atlassian.net/browse/NET-974)

[NET-974 ] Exportd regex condition and limited transfer

---

app/src/app/framework/services/type.service.ts
app/src/app/layout/structure/sidebar/sidebar.component.ts

[[NET-1021] ](https://nethinks.atlassian.net/browse/NET-1021)
[NET-1021]: https://nethinks.atlassian.net/browse/NET-1021

[NET-1021] Show uncategorised and deactivated types in sidebar.

---

app/src/app/search/search-result/search-result-bar/search-result-bar.component.ts
cmdb/framework/cmdb_render.py
cmdb/search/search_result.py

[[NET-1012] ](https://nethinks.atlassian.net/browse/NET-1012)
[NET-1012]: https://nethinks.atlassian.net/browse/NET-1012

[NET-1012] Correction of the resolution of summary fields.

---

cmdb/__setup__.py
cmdb/docapi/docapi_template/docapi_template_manager.py
cmdb/exportd/exportd_job/exportd_job_manager.py
cmdb/exportd/exportd_logs/exportd_log_manager.py
cmdb/exportd/service.py
cmdb/framework/cmdb_object_manager.py
cmdb/framework/cmdb_render.py
cmdb/framework/managers/log_manager.py
cmdb/framework/managers/object_link_manager.py
cmdb/framework/models/link.py
cmdb/framework/models/type.py
cmdb/importer/importer_base.py
cmdb/importer/importer_object.py
cmdb/interface/response.py
cmdb/interface/rest_api/auth_routes.py
cmdb/interface/rest_api/exportd_routes/exportd_job_routes.py
cmdb/interface/rest_api/framework_routes/category_routes.py
cmdb/interface/rest_api/framework_routes/object_routes.py
cmdb/interface/rest_api/framework_routes/type_routes.py
cmdb/interface/rest_api/importer_routes/importer_type_routes.py
cmdb/interface/rest_api/user_management_routes/user_routes.py
cmdb/media_library/media_file_manager.py
cmdb/security/auth/providers/external_providers.py
cmdb/security/token/generator.py
cmdb/user_management/models/user.py

[[NET-1022]](https://nethinks.atlassian.net/browse/NET-1022)
[NET-1022]: https://nethinks.atlassian.net/browse/NET-1022

[NET-1022] Change from datetime.now() to datetime.now(timezone.utc)

---

app/src/app/framework/models/cmdb-type.ts
app/src/app/framework/type/type-builder/type-builder.component.ts
app/src/app/framework/type/type-delete/type-delete.component.ts
app/src/app/framework/type/type.component.html
app/src/app/framework/type/type.component.ts
app/src/app/framework/type/type.module.ts
cmdb/framework/models/type.py
cmdb/interface/rest_api/framework_routes/type_routes.py

[[NET-1006] ](https://nethinks.atlassian.net/browse/NET-1006)
[NET-1006]: https://nethinks.atlassian.net/browse/NET-1006

[NET-1006] Types extended by properties editor_id and last_edit_time.

---

app/src/app/search/search.component.ts

[[NET-1023]](https://nethinks.atlassian.net/browse/NET-1023) 
[NET-1023]: https://nethinks.atlassian.net/browse/NET-1023

[NET-1023] Skip pagination reset.

---

app/src/app/framework/type/builder/builder.component.ts

[NET-1024](https://nethinks.atlassian.net/browse/NET-1024)

[NET-1024] Fix removeField function uses item.name instead of item

---

app/src/app/framework/render/fields/special/ref.component.html
app/src/app/framework/render/fields/special/ref.component.ts
cmdb/framework/cmdb_render.py
cmdb/framework/models/type.py

[[NET-1025]](https://nethinks.atlassian.net/browse/NET-1025)
[NET-1025]: https://nethinks.atlassian.net/browse/NET-1025

[NET-1025] Show references with summaries.

---

app/src/app/framework/models/cmdb-type-reference.ts
app/src/app/framework/object/components/object-actions/object-actions.component.ts
app/src/app/framework/object/components/object-log-list/object-log-change-view/object-log-change-view.component.ts
app/src/app/framework/render/fields/choice/checkbox.component.html
app/src/app/framework/render/fields/special/ref.component.html
app/src/app/framework/render/fields/special/ref.component.scss
app/src/app/framework/render/fields/special/ref.component.ts
app/src/app/framework/render/simple/special/ref-simple.component.html
app/src/app/framework/render/simple/special/ref-simple.component.ts

[[NET-1026]](https://nethinks.atlassian.net/browse/NET-1026)
[NET-1026]: https://nethinks.atlassian.net/browse/NET-1026

[NET-1026] Cleanup: Warnings browser console.

---

cmdb/exportd/externals/external_systems.py

[[NET-1027] ](https://nethinks.atlassian.net/browse/NET-1027)
[NET-1027]: https://nethinks.atlassian.net/browse/NET-1027

[NET-1027] Exportd add event to all external Systems.

---

app/src/app/framework/render/render.component.ts
app/src/app/framework/render/sections/base-section/base-section.component.ts
app/src/app/framework/render/sections/reference-section/reference-section.component.ts

[[NET-1028]](https://nethinks.atlassian.net/browse/NET-1028) 
[NET-1028]: https://nethinks.atlassian.net/browse/NET-1028

[NET-1028] Default-value are not setting automatic on create object

---

.github/workflows/continous-integration.yml
requirements.txt

[NET-794](https://nethinks.atlassian.net/browse/NET-794)

[NET-794] Update crypto packages

---

app/src/app/framework/render/fields/section/ref-section.component.html
app/src/app/framework/render/fields/section/ref-section.component.ts
app/src/app/framework/type/builder/configs/section/section-ref-field-edit.component.html
app/src/app/framework/type/builder/configs/section/section-ref-field-edit.component.ts

[[NET-1054] ](https://nethinks.atlassian.net/browse/NET-1054)
[NET-1054]: https://nethinks.atlassian.net/browse/NET-1054

[NET-1054] Making section reference searchable

---

app/src/app/framework/type/builder/configs/choice/choice-field-edit.component.html
app/src/app/framework/type/builder/configs/choice/choice-field-edit.component.ts

[[NET-1061]](https://nethinks.atlassian.net/browse/NET-1061)
[NET-1061]: https://nethinks.atlassian.net/browse/NET-1061

[NET-1061] Load predefined option at typegenerator.

---

app/src/app/framework/services/object.service.ts
app/src/app/services/api-call.service.ts
cmdb/interface/rest_api/__init__.py
cmdb/interface/rest_api/framework_routes/object_routes.py
cmdb/templates/template_data.py

[[NET-1062] ](https://nethinks.atlassian.net/browse/NET-1062)
[NET-1062]: https://nethinks.atlassian.net/browse/NET-1062

[NET-1062] Update blueprints for object routes.

---

app/src/app/framework/render/fields/section/ref-section.component.html
app/src/app/framework/type/builder/configs/section/section-ref-field-edit.component.ts
app/src/app/services/api-call.service.ts
cmdb/framework/cmdb_render.py
cmdb/templates/template_data.py

[[NET-1063]](https://nethinks.atlassian.net/browse/NET-1063)
[NET-1063]: https://nethinks.atlassian.net/browse/NET-1063

[NET-1063] Resolve Reference-Fields at the Doc-API.

---

app/src/app/framework/object/object-bulk-change/object-bulk-change-preview/object-bulk-change-preview.component.html
app/src/app/framework/object/object-bulk-change/object-bulk-change.component.scss
app/src/app/framework/render/components/input-appends/input-appends.component.html
app/src/app/framework/render/components/object-bulk-input-appends/object-bulk-input-appends.component.html
app/src/app/framework/render/fields/choice/checkbox.component.html
app/src/app/framework/render/fields/choice/radio.component.html
app/src/app/framework/render/fields/section/ref-section.component.html
app/src/app/framework/render/fields/section/ref-section.component.scss
app/src/app/framework/render/fields/section/ref-section.component.ts
app/src/app/framework/render/fields/special/ref.component.html
app/src/app/framework/render/fields/special/ref.component.scss
app/src/app/framework/render/simple/date/date-simple.component.html
app/src/app/framework/render/simple/date/date-simple.component.ts
app/src/app/framework/render/simple/special/ref-section-simple.component.html
app/src/app/layout/pipes/date-formatter.pipe.ts
cmdb/framework/cmdb_render.py

[[NET-1064]](https://nethinks.atlassian.net/browse/NET-1064)
[NET-1064]: https://nethinks.atlassian.net/browse/NET-1064

[NET-1064] Resolve reference-section-fields during bulk change.

---

app/src/app/framework/render/components/input-appends/input-appends.component.html
app/src/app/framework/render/sections/base-section/base-section.component.ts

[[NET-1065]](https://nethinks.atlassian.net/browse/NET-1065)
[NET-1065]: https://nethinks.atlassian.net/browse/NET-1065

[NET-1065] Default values are not set

---

cmdb/exportd/exportd_job/exportd_job_manager.py
docs/source/admin_guide/exportd.rst
docs/source/admin_guide/framework.rst

[[NET-1020]](https://nethinks.atlassian.net/browse/NET-1020)
[NET-1020]: https://nethinks.atlassian.net/browse/NET-1020

[NET-1020] Extension of the documentation for exportd.

---

app/src/app/dashboard/dashboard.component.ts
app/src/app/layout/services/sidebar.service.ts
app/src/app/layout/structure/sidebar/sidebar-category.component.html
app/src/app/layout/structure/sidebar/sidebar-category.component.ts
app/src/app/layout/structure/sidebar/sidebar-type.component.ts

[[NET-1066]](https://nethinks.atlassian.net/browse/NET-1066)
[NET-1066]: https://nethinks.atlassian.net/browse/NET-1066

[NET-1066] Load number of objects when opening the category points.

---

app/src/app/framework/object/components/object-references/object-references-by-type/object-references-by-type.component.html
app/src/app/framework/object/components/object-references/object-references-by-type/object-references-by-type.component.ts
app/src/app/framework/object/components/object-references/object-references-table/object-references-table.component.html
app/src/app/framework/object/components/object-references/object-references-table/object-references-table.component.ts
app/src/app/framework/object/objects-by-type/objects-by-type.component.ts

[[NET-940]](https://nethinks.atlassian.net/browse/NET-940)
[NET-940]: https://nethinks.atlassian.net/browse/NET-940

[NET-940] Object reference field values made searchable.

---

app/src/app/framework/object/object.component.ts

[[NET-1067]](https://nethinks.atlassian.net/browse/NET-1067)
[NET-1067]: https://nethinks.atlassian.net/browse/NET-1067

[NET-1067] Filter over reference field values at the object list.

---

docs/source/admin_guide/framework.rst

[[NET-1068]](https://nethinks.atlassian.net/browse/NET-1068)
[NET-1068]: https://nethinks.atlassian.net/browse/NET-1068

[NET-1068] Admin Guide: Object table filter.

---

app/src/app/framework/type/type-builder/type-meta-step/type-meta-step.component.ts

[[NET-1070]](https://nethinks.atlassian.net/browse/NET-1070) 
[NET-1070]: https://nethinks.atlassian.net/browse/NET-1070

[NET-1070] Expand the selection of the metadata for the external links and the summaries by the entry Object-ID

---

app/src/app/framework/type/builder/builder.component.html
app/src/app/framework/type/builder/builder.component.scss
app/src/app/framework/type/builder/builder.component.ts
app/src/app/framework/type/type-builder/type-meta-step/type-meta-step.component.ts

[[NET-1073]](https://nethinks.atlassian.net/browse/NET-1073)
[NET-1073]: https://nethinks.atlassian.net/browse/NET-1073

[NET-1073] User is notified when a type field is used in an external link

---

app/src/app/framework/object/components/object-log-list/object-log-change-view/object-log-change-view.component.html
app/src/app/framework/object/components/object-log-list/object-log-change-view/object-log-change-view.component.ts
app/src/app/framework/render/components/input-appends/input-appends.component.html
app/src/app/framework/render/fields/date/date.component.html
app/src/app/framework/render/fields/date/date.component.ts
app/src/app/framework/render/fields/section/ref-section.component.html
app/src/app/framework/render/fields/section/ref-section.component.ts
app/src/app/framework/render/fields/special/ref.component.html
app/src/app/framework/render/simple/special/ref-section-simple.component.html
app/src/app/framework/render/simple/special/ref-simple.component.html
app/src/app/framework/render/simple/special/ref-simple.component.ts
app/src/app/framework/type/builder/configs/date-time/date-field-edit.component.html
app/src/app/framework/type/builder/configs/date-time/date-field-edit.component.ts
app/src/app/framework/type/type-builder/type-meta-step/type-meta-step.component.html
app/src/app/framework/type/type-builder/type-meta-step/type-meta-step.component.ts
app/src/app/settings/log-settings/log-object-settings/activate-tab/activate-tab.component.html
app/src/app/settings/log-settings/log-object-settings/activate-tab/activate-tab.component.ts
app/src/app/settings/log-settings/log-object-settings/deactivate-tab/deactivate-tab.component.html
app/src/app/settings/log-settings/log-object-settings/deactivate-tab/deactivate-tab.component.ts
app/src/app/settings/log-settings/log-object-settings/delete-tab/delete-tab.component.html

[[NET-450]](https://nethinks.atlassian.net/browse/NET-450)

[NET-450] Uniform date formatting of all date values in the frontend.

---

cmdb/framework/cmdb_render.py

[[NET-1071]](https://nethinks.atlassian.net/browse/NET-1071)
[NET-1071]: https://nethinks.atlassian.net/browse/NET-1071

[NET-1071] Evaluating the summary values of two references within a type section

---

cmdb/framework/cmdb_render.py

[[NET-1076]](https://nethinks.atlassian.net/browse/NET-1076)
[NET-1076]: https://nethinks.atlassian.net/browse/NET-1076

[NET-1076] Type fields are checked for summaries. Empty list is returned as default.

---

app/src/app/framework/render/fields/special/ref.component.html
app/src/app/framework/type/builder/configs/special/ref-field-edit.component.html
app/src/app/framework/type/builder/configs/special/ref-field-edit.component.ts

[[NET-1055]](
https://nethinks.atlassian.net/browse/NET-1055)
[NET-1055]: https://nethinks.atlassian.net/browse/NET-1055

[NET-1055] Reloading the reference values for the reference-fields in the type generetor.

---

app/src/app/framework/object/object-bulk-change/object-bulk-change.component.ts
app/src/app/framework/render/components/input-appends/input-appends.component.ts
cmdb/framework/cmdb_object.py
cmdb/framework/cmdb_object_manager.py
cmdb/framework/managers/object_manager.py
cmdb/framework/managers/type_manager.py
cmdb/interface/response.py
cmdb/interface/rest_api/framework_routes/object_routes.py
cmdb/interface/rest_api/importer_routes/importer_type_routes.py
cmdb/manager/__init__.py
cmdb/updater/updater.py
cmdb/updater/versions/updater_20200214.py
cmdb/updater/versions/updater_20200226.py
tests/functional/framework/test_functional_objects.py

[[NET-639] ](https://nethinks.atlassian.net/browse/NET-639)
[NET-639]: https://nethinks.atlassian.net/browse/NET-639

[NET-639] Migrate object new api update

---

app/src/app/framework/object/components/object-log-list/object-log-change-view/object-log-change-view.component.html
app/src/app/framework/object/components/object-log-list/object-log-change-view/object-log-change-view.component.ts

[[NET-1088]](https://nethinks.atlassian.net/browse/NET-1088)
[NET-1088]: https://nethinks.atlassian.net/browse/NET-1088

[NET-1088] Check changes for completeness.

---

app/src/app/framework/object/object-bulk-change/object-bulk-change-complete/object-bulk-change-complete.component.html
app/src/app/framework/object/object-bulk-change/object-bulk-change-complete/object-bulk-change-complete.component.ts
app/src/app/framework/object/object-bulk-change/object-bulk-change-complete/object-bulk-change-failed/object-bulk-change-failed.component.html
app/src/app/framework/object/object-bulk-change/object-bulk-change-complete/object-bulk-change-failed/object-bulk-change-failed.component.ts
app/src/app/framework/object/object-bulk-change/object-bulk-change.component.html
app/src/app/framework/object/object-bulk-change/object-bulk-change.component.ts
app/src/app/framework/object/object-edit/object-edit.component.ts
app/src/app/framework/object/object.module.ts
app/src/app/framework/services/object.service.ts
app/src/app/services/models/api-response.ts
cmdb/interface/response.py
cmdb/interface/rest_api/framework_routes/object_routes.py

[[NET-1074]](https://nethinks.atlassian.net/browse/NET-1074)
[NET-1074]: https://nethinks.atlassian.net/browse/NET-1074

[NET-1074] Exception handling bulk changes

---

cmdb/framework/cmdb_render.py
tests/functional/framework/test_functional_objects.py

[[NET-1090]](https://nethinks.atlassian.net/browse/NET-1090)
[NET-1090]: https://nethinks.atlassian.net/browse/NET-1090

[NET-1090] Use default summary line if field not found th the input type

---

cmdb/search/searchers.py

[[NET-1079] ](https://nethinks.atlassian.net/browse/NET-1079)
[NET-1079]: https://nethinks.atlassian.net/browse/NET-1079

[NET-1079] Fields from the referenced object are merged with the fields from the found object.

---

app/src/app/framework/render/fields/section/ref-section.component.html
cmdb/framework/cmdb_render.py

[[NET-1077]](https://nethinks.atlassian.net/browse/NET-1077)
[NET-1077]: https://nethinks.atlassian.net/browse/NET-1077

[NET-1077] referencing to referencing

---

app/src/app/layout/directives/preventDoubleSubmit.directive.ts
app/src/app/layout/layout.module.ts

[[NET-1108]](https://nethinks.atlassian.net/browse/NET-1108) 
[NET-1108]: https://nethinks.atlassian.net/browse/NET-1108

[NET-1108] Prevent double submit.

---

app/src/app/layout/directives/preventDoubleSubmit.directive.ts

[[NET-1117]](https://nethinks.atlassian.net/browse/NET-1117)
[NET-1117]: https://nethinks.atlassian.net/browse/NET-1117

[NET-1117] Submit button trigger saving when 'ENTER' pressed.

---

cmdb/framework/models/type.py
tests/functional/framework/test_functional_types.py

[[NET-1119]](https://nethinks.atlassian.net/browse/NET-1119) 
[NET-1119]: https://nethinks.atlassian.net/browse/NET-1119

[NET-1119] Extension of the validation schema for the field definition by type generator.

---

cmdb/framework/cmdb_object_manager.py
cmdb/interface/response.py
cmdb/interface/rest_api/__init__.py
cmdb/interface/route_utils.py
cmdb/security/auth/response.py
requirements.txt

- bumped flask==2.3.2
- bumped itsdangerous==2.1.2
- bumped Jinja2==3.1.2
- bumped MarkupSafe==2.1.3
- bumped Sphinx==4.5.0
- bumped Werkzeug==2.3.6
- - added blinker==1.6.2
- fixed some pylint warnings

[DAT-430] Bump flask to 2.3.2

---

requirements.txt

Bumps:
alabaster==0.7.13
altgraph==0.17.3

[DAT-479][DAT-480] bump old versions

---

cmdb/interface/rest_api/__init__.py
cmdb/interface/rest_api/external_systems_routes.py
cmdb/interface/rest_api/framework_routes/object_routes.py
requirements.txt

Bumped:
- Cerberus 1.3.2 => 1.3.4
- certifi 2022.12.7. => 2023.5.7
- PyPDF2 1.27.5 => 1.28.6
Fixed some pylint warnings

[DAT-481] Bumped PyPDF2 to 1.28.6

---

requirements.txt

Bumped:
- ldap3 to 2.9.1
- pyMySQL to 1.1.0
- et-xmlfile to 1.1.0

DAT-487_bump-ldap3-to-2.9.1

---

requirements.txt

Bumped:
- chardet to 5.1.0
- iniconfig to 2.0.0
- isort to 5.12.0

[DAT-489] Bump chardet to 5.1.0

---

requirements.txt

Bumped:
- gunicorn to 20.1.0
- Pillow to 10.0.0
- Pygments to 2.15.1

[DAT-513] Bump guicorn to 20.1.0

---

docs/source/conf.py
docs/theme/sphinx_dg_theme/_navigation.html
requirements.txt

Bumped:
* Sphinx to 7.0.1
* docutils to 0.20.1

[DAT-531] Bump Sphinx to 7.0.1

---

app/package-lock.json
app/package.json
app/src/app/layout/structure/sidebar/sidebar.component.html
app/src/app/layout/structure/sidebar/sidebar.component.scss

- Bumped socket.io-parser to 4.2.4
- fixed sidebar filter

[DAT-533] Bumped socket.io-parser to 4.2.4

---

app/src/scss/_layout.scss

Bugs fixed:
* Filter not visible in mobile view (https://becon88.atlassian.net/browse/DAT-537)
* Sidebar z-index to low in mobile view (https://becon88.atlassian.net/browse/DAT-403)

[DAT-537] Filter field not visible in mobile view

---

app/.editorconfig
app/src/app/framework/render/fields/special/location.component.html
app/src/app/framework/render/fields/special/location.component.ts
app/src/app/framework/services/location.service.ts
app/src/app/layout/structure/sidebar/category-tree/category-tree.component.ts
cmdb/database/managers.py
cmdb/framework/cmdb_base.py
cmdb/framework/cmdb_location.py
cmdb/framework/cmdb_location_manager.py
cmdb/interface/rest_api/framework_routes/location_routes.py
cmdb/interface/rest_api/framework_routes/type_routes.py
cmdb/interface/rest_api/framework_routes/types_routes.py

Changes:
* When updating a location, the object_id will be overwritten with the new location
* When editing a type, all root locations with that type will be updated (label, icon, selectable).
* A location is only deletable if it has no children

[DAT-540] location handling

---

app/src/app/framework/render/fields/special/location.component.html
app/src/app/framework/render/fields/special/location.component.ts
app/src/app/layout/structure/sidebar/category-tree/category-tree.component.html
app/src/app/layout/structure/sidebar/category-tree/category-tree.component.scss

Changes:
* Bulk changes for locations removed
* Adapted visualisation of location tree in sidebar

[DAT-541] bulk changes

---

app/src/app/framework/services/type.service.ts
app/src/app/framework/type/type-delete/type-delete.component.html
app/src/app/framework/type/type-delete/type-delete.component.scss
app/src/app/framework/type/type-delete/type-delete.component.ts
app/src/app/layout/structure/sidebar/category-tree/category-tree.component.html
app/src/app/layout/structure/sidebar/category-tree/category-tree.component.scss
app/src/scss/_variables.scss
cmdb/framework/managers/object_manager.py
cmdb/interface/rest_api/framework_routes/objects_routes.py
cmdb/interface/rest_api/framework_routes/types_routes.py

Changes:
* Types can only be deleted if there are no exisiting objects of that type

[DAT-542] Type Deletion workflow

---

app/src/app/framework/object/components/object-summary/object-summary.component.html
app/src/app/framework/object/components/object-summary/object-summary.component.ts

- Errors when copying dates to the clipboard

Date copy issue solved

---

app/src/app/export/export-objects/export-objects.component.html
app/src/app/export/export-objects/export-objects.component.ts

DAT-461 ⁃ Error displayed although successful execution

Error displayed although successful execution Solved

---

app/src/app/framework/render/fields/textarea/textarea.component.html
app/src/app/framework/render/fields/textarea/textarea.component.scss

Fix the size of the UI elements so the size is suitable to be used. Infors in post

Fix the size of the UI elements so the size is suitable to be used.

---

app/src/app/settings/log-settings/log-object-settings/log-object-settings.component.ts

DAT-447 ⁃ Error when closing Delete popup for Object logs

Hotfix/dat 447⁃error delete popup object logs

---

app/src/app/framework/object/components/object-references/object-references.component.ts

Viewing referenced item to fast causes an error

DAT-457 ⁃ Viewing referenced item to fast causes an error

---

app/src/app/dashboard/dashboard.component.ts

Fixed UI display bug for types

Bugfix/dat 470⁃UI display bug for types

---

app/src/app/framework/object/modals/object-delete-modal/object-delete-modal.component.html
app/src/app/framework/object/modals/object-delete-modal/object-delete-modal.component.ts

DAT-454 ⁃ Error when closing delete dialog in object list

DAT-454 ⁃ Error when closing delete dialog in object list

---

app/src/app/layout/table/table.component.ts

Fixed: Counter for bulk change /delete selected is stacked

DAT-451 ⁃ Counter for bulk change /delete selected is stacked

---

app/src/app/dashboard/dashboard.component.ts
app/src/app/framework/object/components/object-actions/object-actions.component.ts
app/src/app/framework/object/modals/objects-delete-modal/objects-delete-modal.component.html
app/src/app/framework/object/object.component.html
app/src/app/framework/object/object.component.ts
app/src/app/framework/object/objects-by-type/objects-by-type.component.ts
app/src/app/framework/render/fields/special/location.component.ts
app/src/app/framework/services/object.service.ts
app/src/app/layout/toast/toast-container/toast-container.component.ts
cmdb/framework/cmdb_base.py
cmdb/framework/cmdb_location_manager.py
cmdb/interface/api_parameters.py
cmdb/interface/rest_api/framework_routes/location_routes.py
cmdb/interface/rest_api/framework_routes/objects_routes.py

Changes:
* deleteing objects with locations which have child locations (only child locations)
* deleteing objects with locations which have child locations (child objects and child locations)
* no bulk delete of objects with locations
* increased general toast visibility time

DAT-545-delete-multiple-objects-workflow

---

app/src/app/auth/services/auth.service.ts
app/src/app/layout/intro/intro.component.html
app/src/app/layout/intro/intro.component.ts
app/src/app/layout/structure/navigation/navigation.component.html
app/src/app/layout/structure/navigation/navigation.component.scss
app/src/app/layout/structure/navigation/navigation.component.ts

Changes:
* Icon for assistant in toolbox
* alternative modal for assistant in tool box when not usable
* alternative text on initial popup for assistant

DAT-395-icon-for-assitant

---

app/src/app/auth/services/auth.service.ts
app/src/app/framework/object/object-copy/object-copy.component.ts
app/src/app/framework/render/fields/special/location.component.ts
app/src/app/framework/services/location.service.ts
app/src/app/layout/intro/branch-info-modal/branch-info-modal.component.html
app/src/app/layout/intro/branch-info-modal/branch-info-modal.component.scss
app/src/app/layout/intro/branch-info-modal/branch-info-modal.component.ts
app/src/app/layout/intro/intro.component.html
app/src/app/layout/layout.module.ts
app/src/app/layout/structure/navigation/navigation.component.ts
app/src/app/layout/structure/sidebar/location-tree/location-tree.component.ts

Changes:
* Fixed label bug in object overview for locations
* added new route for intro assistant
* created modal for branch selection in assistant workflow
* improved texts for intro sections

DAT-393-new-paths-for-intro

---

app/src/app/auth/services/auth.service.ts
app/src/app/layout/intro/branch-info-modal/branch-info-modal.component.html
app/src/app/layout/intro/profile-info-modal/profile-info-modal.component.html
app/src/app/layout/intro/profile-info-modal/profile-info-modal.component.scss
app/src/app/layout/intro/profile-info-modal/profile-info-modal.component.ts
app/src/app/layout/layout.module.ts

Changes:
* branch selection page for assistant with reactive form
* profile selection page for assitant with reactive form

DAT-405-assistant-profile-page

---

app/src/app/auth/services/auth.service.ts
app/src/app/framework/services/special.service.ts
app/src/app/layout/intro/branch-info-modal/branch-info-modal.component.html
app/src/app/layout/intro/branch-info-modal/branch-info-modal.component.ts
app/src/app/layout/intro/intro.component.html
app/src/app/layout/intro/profile-info-modal/profile-info-modal.component.html
app/src/app/layout/intro/profile-info-modal/profile-info-modal.component.ts
app/src/app/layout/structure/navigation/navigation.component.html
cmdb/framework/assistant_profiles/profiles.py
cmdb/interface/blueprint.py
cmdb/interface/rest_api/framework_routes/type_routes.py
cmdb/interface/rest_api/framework_routes/types_routes.py
cmdb/interface/rest_api/import_routes.py
cmdb/interface/rest_api/importer_routes/importer_type_routes.py
cmdb/interface/rest_api/special_routes.py

Changes:
* Dynamic profile list in front
* Creation of types from selected profiles in backend
* Assistant icon changed
* New order of buttons (Positive action is most right button)

DAT-415-handle-profiles

---

app/src/app/framework/type/services/validation.service.ts

comments added for every method in validationService

comments added for every method in validationService

---

app/src/app/framework/services/type.service.ts

fixed: DAT-551 ⁃ Sidebar not updated when deleting a type

Fixed: Sidebar not updated when deleting a type

---

app/src/app/auth/services/auth.service.ts
app/src/app/framework/type/builder/configs/special/location-field-edit.component.html
app/src/app/framework/type/builder/configs/special/location-field-edit.component.ts
app/src/app/framework/type/type-builder/type-meta-step/type-meta-step.component.html
app/src/app/framework/type/type-builder/type-meta-step/type-meta-step.component.ts
app/src/app/layout/intro/branch-info-modal/branch-info-modal.component.html
app/src/app/layout/intro/branch-info-modal/branch-info-modal.component.ts
app/src/app/layout/intro/profile-info-modal/profile-info-modal.component.ts
cmdb/framework/assistant_profiles/profile_base_class.py
cmdb/framework/assistant_profiles/profile_client_management.py
cmdb/framework/assistant_profiles/profile_ipam.py
cmdb/framework/assistant_profiles/profile_location.py
cmdb/framework/assistant_profiles/profile_network_infrastructure.py
cmdb/framework/assistant_profiles/profile_server_management.py
cmdb/framework/assistant_profiles/profile_user_management.py
cmdb/framework/assistant_profiles/profiles.py
cmdb/interface/rest_api/special_routes.py

Changes:
* final profiles in frontend
* final profiles in backend
* fixed issue with location creation while creating a type

DAT-552-assistant-improvements

---

requirements.txt

Changes:
* Bumps Babel to 2.13.1
* Bumps blinker to 1.7.0
* Bumps Cerberus to 1.3.5

several-bumps-for-python

---

app/src/app/framework/render/simple/choice/select-simple.component.html
app/src/app/framework/render/simple/choice/select-simple.component.ts

Fixed: Overview displays Selection field value instead of label

Fixed Overview displays Selection field value instead of label

---

requirements.txt

Changes:
* Bumped flake8 to 6.1.0
* Bumped pycodestyle to 2.11.1
* Bumped pyflakes to 3.1.0

DAT-585 bump flake8 to 6.1.0

---

requirements.txt

Changes:
* Bumped guicorn to 21.2.0
* Bumped packaging to 23.2
* Bumped pluggy to 1.3.0

DAT-588-Bump gunicorn to 21.2.0

---

requirements.txt

Changes:
* Bumped pyinstaller to 6.1.0
* Bumped pyinstaller-hooks.contrib to 2023.10

DAT-602-bump-pyinstaller-to-6.1.0

---

cmdb/__check__.py
cmdb/__main__.py
cmdb/__setup__.py
cmdb/__update__.py
cmdb/framework/__init__.py
cmdb/framework/cmdb_dao.py
cmdb/framework/cmdb_location.py
cmdb/framework/cmdb_object.py
cmdb/framework/cmdb_section_template.py
cmdb/updater/updater.py
cmdb/updater/versions/updater_20200512.py
cmdb/utils/error.py

Changes:
* Added Section Template Model to Backend
* New collection for section templates will be created in the workflow
* Refachtoring of multiple files

DAT-649 section template model added

---

app/src/app/framework/models/cmdb-section-template.ts
app/src/app/layout/structure/sidebar/sidebar.component.ts
cmdb/__check__.py
cmdb/__main__.py
cmdb/database/connection.py
cmdb/database/managers.py
cmdb/framework/assistant_profiles/profile_location.py

Changes:
* Added section template model to frontend
* Fixed assistant type not initially not selectable
* Fixed startup routine path where root location was not created if it didn't exist

DAT-651 Add section template model to frontend

---

app/src/app/dashboard/dashboard.component.ts

Solved: DAT-553 ⁃ Display uncagetorised types in dashboard overview

Populating UNCATEGORIZED in types overview

---

cmdb/database/connection.py
cmdb/database/database_manager.py
cmdb/database/database_manager_mongo.py
cmdb/framework/cmdb_base.py
cmdb/framework/cmdb_location_manager.py
cmdb/interface/rest_api/__init__.py
cmdb/interface/rest_api/framework_routes/location_routes.py
cmdb/interface/rest_api/framework_routes/section_template_routes.py
cmdb/manager/__init__.py

Changes:
* Added section template API routes blueprint
* Refactoring of DatabaseManager and DatabaseManagerMongo

DAT-654-Create section template API

---

app/src/app/framework/object/components/object-links-table/object-links-table.component.ts

DAT-571 ⁃ Error when closing "Add Link" Popup

solved: Error when closing "Add Link" Popup

---

app/src/app/management/user-settings/services/user-settings-db.service.ts

Error pressing Edit button in categories

Error pressing Edit button in categories

---

app/src/app/framework/models/cmdb-section-template.ts
app/src/app/framework/section_templates/layout/section-template-add/section-template-add.component.html
app/src/app/framework/section_templates/layout/section-template-add/section-template-add.component.ts
app/src/app/framework/section_templates/layout/section-template-builder/section-template-builder.component.html
app/src/app/framework/section_templates/layout/section-template-builder/section-template-builder.component.scss
app/src/app/framework/section_templates/layout/section-template-builder/section-template-builder.component.ts
app/src/app/framework/section_templates/section-template-routing.module.ts
app/src/app/framework/section_templates/section-template.component.html
app/src/app/framework/section_templates/section-template.module.ts
app/src/app/framework/type/builder/builder.module.ts
app/src/app/framework/type/builder/configs/config-edit.component.ts

Changes:
* Added section template creation page

DAT-658 add creation page

---

app/src/app/framework/section_templates/layout/section-template-builder/section-template-builder.component.html
app/src/app/framework/section_templates/layout/section-template-builder/section-template-builder.component.ts
app/src/app/framework/section_templates/section-template.module.ts
app/src/app/framework/section_templates/services/section-template.service.ts
cmdb/framework/cmdb_errors.py
cmdb/framework/cmdb_section_template_manager.py
cmdb/interface/rest_api/framework_routes/section_template_routes.py

Changes:
* Added storage of section templates in database after creation

DAT-663-API connection for creation of section templates

---

app/src/app/framework/object/modals/object-delete-modal/object-delete-modal.component.html
app/src/app/framework/section_templates/layout/modals/section-template-delete/section-template-delete-modal.component.html
app/src/app/framework/section_templates/layout/modals/section-template-delete/section-template-delete-modal.component.ts
app/src/app/framework/section_templates/layout/section-template-add/section-template-add.component.html
app/src/app/framework/section_templates/layout/section-template-add/section-template-add.component.ts
app/src/app/framework/section_templates/layout/section-template-builder/section-template-builder.component.html
app/src/app/framework/section_templates/layout/section-template-builder/section-template-builder.component.ts
app/src/app/framework/section_templates/section-template-routing.module.ts
app/src/app/framework/section_templates/section-template.component.html
app/src/app/framework/section_templates/section-template.component.scss
app/src/app/framework/section_templates/section-template.component.ts
app/src/app/framework/section_templates/section-template.module.ts
app/src/app/framework/section_templates/services/section-template.service.ts
cmdb/framework/cmdb_section_template_manager.py
cmdb/framework/managers/query_builders/default_query_builder.py
cmdb/framework/managers/section_template_manager.py
cmdb/interface/rest_api/framework_routes/section_template_routes.py

Changes:
* editing of section templates added
* deleting of section templates added
* modal view for deleting confirmation added
* displaying all section templates in table added

DAT-664 section template table apis

---

app/src/app/framework/object/object.component.ts
app/src/app/framework/type/builder/builder.component.html
app/src/app/framework/type/builder/builder.component.scss
app/src/app/framework/type/builder/builder.component.ts
app/src/app/framework/type/builder/configs/special/location-field-edit.component.ts
app/src/app/framework/type/type-builder/type-fields-step/type-fields-step.component.html
app/src/app/framework/type/type-builder/type-fields-step/type-fields-step.component.ts

Changes:
* added section template handling to type configuration

DAT-665-add-section-templates-to-type-config

---

app/src/app/framework/object/components/object-summary/object-summary.component.html
app/src/app/framework/object/components/object-summary/object-summary.component.ts

- Solved the clipboard issue
- execcommand deprecated! So, I used a navigator library to tackle it!

clipboard issue solved

---

app/src/app/framework/modes.enum.ts
app/src/app/framework/section_templates/layout/modals/section-template-transform/section-template-transform-modal.component.html
app/src/app/framework/section_templates/layout/modals/section-template-transform/section-template-transform-modal.component.scss
app/src/app/framework/section_templates/layout/modals/section-template-transform/section-template-transform-modal.component.ts
app/src/app/framework/section_templates/layout/section-template-builder/section-template-builder.component.html
app/src/app/framework/section_templates/layout/section-template-builder/section-template-builder.component.ts
app/src/app/framework/section_templates/section-template.component.html
app/src/app/framework/section_templates/section-template.component.scss
app/src/app/framework/section_templates/section-template.component.ts
app/src/app/framework/section_templates/section-template.module.ts
app/src/app/framework/type/builder/builder.component.html
app/src/app/framework/type/builder/builder.component.ts
app/src/app/framework/type/builder/configs/config.edit.ts
app/src/app/framework/type/builder/configs/section/section-field-edit.component.ts
app/src/app/framework/type/type-builder/type-fields-step/type-fields-step.component.html
app/src/app/framework/type/type-builder/type-fields-step/type-fields-step.component.ts

Changes:
* added global templates to type config
* added transform action for section templates
* locked name and label when editing global templates

DAT-666 add global templates in type config

---

app/src/app/framework/section_templates/layout/modals/section-template-clone/section-template-clone-modal.component.html
app/src/app/framework/section_templates/layout/modals/section-template-clone/section-template-clone-modal.component.scss
app/src/app/framework/section_templates/layout/modals/section-template-clone/section-template-clone-modal.component.ts
app/src/app/framework/section_templates/layout/section-template-builder/section-template-builder.component.ts
app/src/app/framework/section_templates/section-template.component.html
app/src/app/framework/section_templates/section-template.component.scss
app/src/app/framework/section_templates/section-template.component.ts
app/src/app/framework/section_templates/section-template.module.ts
app/src/app/framework/type/builder/builder.component.html
app/src/app/framework/type/builder/builder.component.scss
app/src/app/framework/type/builder/builder.component.ts
app/src/app/framework/type/type-edit/type-edit.component.html

Changes:
* Section templates can now be cloned in the template overview
* in type config the title is now the type label instead of the type name
* global section templates are not editable in type configs

DAT-669 add clone logics

---

app/src/app/framework/type/builder/builder.component.html
app/src/app/framework/type/builder/builder.component.ts
app/src/app/framework/type/builder/configs/choice/check-field-edit.component.ts
app/src/app/framework/type/builder/configs/choice/choice-field-edit.component.html
app/src/app/framework/type/builder/configs/choice/choice-field-edit.component.ts
app/src/app/framework/type/builder/configs/config-edit.component.ts
app/src/app/framework/type/builder/configs/config.edit.ts
app/src/app/framework/type/builder/configs/date-time/date-field-edit.component.html
app/src/app/framework/type/builder/configs/date-time/date-field-edit.component.ts
app/src/app/framework/type/builder/configs/special/ref-field-edit.component.html
app/src/app/framework/type/builder/configs/special/ref-field-edit.component.ts
app/src/app/framework/type/builder/configs/text/text-field-edit.component.html
app/src/app/framework/type/builder/configs/text/text-field-edit.component.ts
app/src/app/framework/type/builder/configs/text/textarea-edit.component.ts
cmdb/__check__.py
cmdb/database/database_manager_mongo.py
cmdb/docapi/docapi_template/docapi_template_manager.py
cmdb/exportd/exportd_job/exportd_job_manager.py
cmdb/framework/cmdb_base.py
cmdb/framework/cmdb_errors.py
cmdb/framework/cmdb_section_template_manager.py
cmdb/framework/section_templates/section_template_creator.py
cmdb/interface/rest_api/exportd_routes/exportd_job_routes.py
cmdb/interface/rest_api/exportd_routes/exportd_log_routes.py
cmdb/interface/rest_api/exporter_routes/exporter_type_routes.py
cmdb/media_library/media_file_manager.py
cmdb/user_management/user_manager.py

Changes:
* Fixed field attribute changes not being saved
* predefined section templates are created on app startup
* Fixed circular dependency in backend
* Code refactoring

DAT-688 field values not saved

---

cmdb/framework/managers/category_manager.py
cmdb/interface/rest_api/framework_routes/categories_routes.py
cmdb/manager/__init__.py

Changes:
* Fixed issue with deleting categories which have children. Now direct children of deleted top categories wil be top categories themself.

DAT-660 improve delete categories

---

Makefile
cmdb/updater/__init__.py
cmdb/updater/updater.py
cmdb/updater/versions/updater_20200214.py
cmdb/updater/versions/updater_20200226.py
cmdb/updater/versions/updater_20200408.py
cmdb/updater/versions/updater_20200512.py
cmdb/updater/versions/updater_20200513.py

Changes:
* added new update which sets 'global_template_ids' and 'selectable_as_parent' to types
* Removed author function from updates
* removed @property annotation for updates

DAT-690 create update for section templates

---

app/src/app/framework/object/objects-by-type/objects-by-type.component.html
app/src/app/layout/table/body/table-cell/table-cell.component.html
app/src/app/layout/table/body/table-cell/table-cell.component.scss
app/src/app/layout/table/body/table-cell/table-cell.component.ts
app/src/app/layout/table/table.component.html
app/src/app/layout/table/table.component.ts

Features Added:
Row clickable to open the object overview
Double-click on a row to enter the edit mode of the object

Improved object table

---

app/src/app/framework/section_templates/layout/section-template-builder/section-template-builder.component.html
app/src/app/framework/section_templates/layout/section-template-builder/section-template-builder.component.ts
app/src/app/framework/type/builder/builder.component.ts
cmdb/interface/rest_api/framework_routes/categories_routes.py
cmdb/manager/categories_manager.py

Changes:
* Fixed additional values not saved for sectin templates
* Fixed global field still editable
* Fixed wrong fields deleted in type config edit form
* added initial CategoriesManager for Backend

DAT-702 additional values not saved

---

app/src/app/settings/log-settings/log-object-settings/activate-tab/activate-tab.component.ts
app/src/app/settings/log-settings/log-object-settings/delete-tab/delete-tab.component.ts
cmdb/interface/rest_api/logs_routes.py

Changes:
* Fixed loading object logs
* Code refactoring

DAT-713-fix-object-logs-not-loaded

---

app/src/app/framework/object/modals/object-link-add-modal/object-link-add-modal.component.html

make the button disable while the form is invalid

make button disable while form is invalid

---

Makefile
cmdb/__check__.py
cmdb/__setup__.py
contrib/docker/Dockerfile
contrib/docker/compose/nossl/docker-compose.yml
contrib/docker/compose/ssl/docker-compose.yml

Changes:
* Updated Dockerfile
* Fixed issue where admin user was not created

Updates for release

---

app/angular.json

'moment' added in "allowedCommonJsDependencies"

warning fixed

---

requirements.txt

Bumped python packages
Changes:
* pyinstaller to 6.5.0
* pyinstaller-hooks-contrib to 2024.3
* packaging to 24.0

DAT-768 bump pyinstaller

---

app/package-lock.json
app/package.json
app/src/app/framework/object/components/object-log-list/object-log-change-view/object-log-change-view.component.ts
app/src/app/framework/object/modals/object-link-delete-modal/object-link-delete-modal.component.ts
app/src/app/framework/object/object-view/object-view.component.ts
app/src/app/layout/progress/progress-bar/progress-bar.types.ts

Changes:
* bumped rxjs to 7.8.1

DAT 774 bump rxjs

---

app/src/app/docapi/docapi-builder/docapi-builder-content-step/docapi-builder-content-step.component.ts

Also, indent space change to 4

license key "gpl" added

---

app/src/app/framework/models/cmdb-type-reference.ts
app/src/app/framework/models/cmdb-type.ts
app/src/app/settings/auth-settings/active-providers.pipe.ts
app/src/app/settings/auth-settings/auth-settings.component.html
app/src/app/settings/auth-settings/auth-settings.component.ts
app/src/app/settings/auth-settings/auth-settings.module.ts
cmdb/framework/models/type.py

Changes:
* Improved Type-model
* Refactor code

DAT-820-improve-type-model

---

app/src/app/framework/type/builder/builder.component.html
app/src/app/framework/type/builder/builder.component.ts
app/src/app/framework/type/builder/configs/choice/check-field-edit.component.ts
app/src/app/framework/type/builder/configs/choice/choice-field-edit.component.ts
app/src/app/framework/type/builder/configs/config-edit.component.ts
app/src/app/framework/type/builder/configs/config.edit.ts
app/src/app/framework/type/builder/configs/date-time/date-field-edit.component.ts
app/src/app/framework/type/builder/configs/text/text-field-edit.component.ts
app/src/app/framework/type/builder/configs/text/textarea-edit.component.ts

Changes:
* Checkbox logics for MDS now working

DAT-826 activate checkboxes

---

app/package-lock.json
app/package.json
app/src/app/framework/object/object-add/object-add.component.html
app/src/app/framework/object/object-edit/object-edit.component.html
app/src/app/framework/object/object-edit/object-edit.component.ts
app/src/app/framework/render/render-element/render-element.component.ts
app/src/app/framework/render/render.component.html
app/src/app/framework/render/render.component.ts
app/src/app/framework/render/render.module.ts
app/src/app/framework/render/sections/base-section/base-section.component.ts
app/src/app/framework/render/sections/field-section/field-section.component.html
app/src/app/framework/render/sections/field-section/field-section.component.ts
app/src/app/framework/render/sections/multi-data-section/multi-data-section.component.html
app/src/app/framework/render/sections/multi-data-section/multi-data-section.component.scss
app/src/app/framework/render/sections/multi-data-section/multi-data-section.component.ts
app/src/app/framework/render/sections/sections-factory/sections-factory.component.html
app/src/app/framework/render/sections/sections-factory/sections-factory.component.ts
app/src/app/framework/render/simple/simple.list.ts
app/src/app/layout/table/table.component.html
cmdb/framework/cmdb_render.py

Changes:
* Added actions and "Add" button for MDS
* refactored MDS in own component

DAT-829 add button for multi-data-sections

---

app/src/app/framework/models/cmdb-object.ts
app/src/app/framework/object/components/object-table-actions/object-table-actions.component.ts
app/src/app/framework/render/render.component.html
app/src/app/framework/render/render.module.ts
app/src/app/framework/render/sections/modals/delete-entry-modal.component.html
app/src/app/framework/render/sections/modals/delete-entry-modal.component.ts
app/src/app/framework/render/sections/multi-data-actions/multi-data-actions.component.html
app/src/app/framework/render/sections/multi-data-actions/multi-data-actions.component.scss
app/src/app/framework/render/sections/multi-data-actions/multi-data-actions.component.ts
app/src/app/framework/render/sections/multi-data-section/multi-data-section.component.html
app/src/app/framework/render/sections/multi-data-section/multi-data-section.component.scss
app/src/app/framework/render/sections/multi-data-section/multi-data-section.component.ts
app/src/app/framework/render/sections/sections-factory/sections-factory.component.html
app/src/app/framework/type/builder/modals/preview-modal/preview-modal.component.html
app/src/app/framework/type/builder/modals/preview-modal/preview-modal.component.ts
app/src/app/layout/table/table.component.ts
app/src/app/modules/info/components/about/about.component.html

Changes:
* Added functionality for the "Add" button for MDS tables
* Added functionality of actions for MDS tables

DAT-838 add button and actions functionality

---

app/src/app/framework/models/cmdb-object.ts
app/src/app/framework/object/object-add/object-add.component.html
app/src/app/framework/object/object-add/object-add.component.ts
app/src/app/framework/render/sections/multi-data-actions/multi-data-actions.component.scss
app/src/app/framework/render/sections/multi-data-section/multi-data-section.component.html
app/src/app/framework/render/sections/multi-data-section/multi-data-section.component.ts

Changes:
* MDS can now be saved to backend via object create form

DAT-839 save mds in backend

---

app/src/app/framework/models/cmdb-object.ts
app/src/app/framework/models/cmdb-render.ts
app/src/app/framework/object/components/object-view-render/object-view-render.component.html
app/src/app/framework/object/components/object-view-render/object-view-render.component.ts
app/src/app/framework/object/object-edit/object-edit.component.ts
app/src/app/framework/object/object-view/object-view.component.html
app/src/app/framework/object/object-view/object-view.component.ts
app/src/app/framework/render/render.component.html
app/src/app/framework/render/sections/multi-data-section/multi-data-section.component.html
app/src/app/framework/render/sections/multi-data-section/multi-data-section.component.ts
app/src/app/framework/render/sections/sections-factory/sections-factory.component.html
app/src/app/framework/render/sections/sections-factory/sections-factory.component.ts
cmdb/framework/cmdb_render.py

Changes:
* Added logics for view and edit mode of MDS

DAT-841 view-edit mds

---

app/src/app/framework/render/sections/multi-data-section/multi-data-section.component.html
app/src/app/framework/render/sections/multi-data-section/multi-data-section.component.ts
app/src/app/framework/render/simple/text/password-simple.component.html
app/src/app/framework/render/simple/text/password-simple.component.ts

Changes:
* Hidden fields for MDS tables are now handled
* Fixed total count for MDS tables
* Fixed password field click-event in object overview table

DAT-851 handle hidden fields

---

app/src/app/framework/render/sections/multi-data-section/multi-data-section.component.ts
app/src/app/framework/type/components/clean-button/clean-button.component.html
app/src/app/framework/type/components/clean-button/clean-button.component.ts
cmdb/event_management/event_manager.py
cmdb/framework/managers/type_manager.py
cmdb/framework/models/type_model/type_field_section.py
cmdb/framework/models/type_model/type_multi_data_section.py
cmdb/interface/rest_api/framework_routes/types_routes.py

Changes:
* handle editing of mds in type config
* updated field handling of mds for all basic controls

DAT-852 handle edit MDS in type config

---

app/src/app/layout/table/components/table-states/table-state.component.html
app/src/app/layout/table/components/table-states/table-state.component.ts
app/src/app/layout/table/table.service.ts
app/src/app/layout/table/table.types.ts
app/src/app/management/user-settings/models/user-setting.ts
app/src/app/management/user-settings/services/user-settings-db.service.ts
cmdb/__check__.py
cmdb/event_management/event_manager.py
cmdb/interface/rest_api/user_management_routes/user_settings_routes.py

Changes:
* improved logging of updater
* improved error logging of RabbitMQ
* Fixed saving column preferences

DAT-837 improve messages for updater

---

app/src/app/framework/render/fields/components.fields.ts
app/src/app/framework/render/fields/special/ref.component.html
app/src/app/framework/render/fields/special/ref.component.ts
app/src/app/framework/render/sections/multi-data-section/multi-data-section.component.ts
app/src/app/framework/services/object.service.ts
cmdb/framework/cmdb_render.py
cmdb/interface/rest_api/framework_routes/objects_routes.py

Changes:
* Added ref-fields functionality for MDS

DAT-849 ref-fields-mds

---

app/src/app/modules/import/components/objects/import-objects/import-objects.component.ts
app/src/app/modules/import/import.component.scss
cmdb/importer/importer_base.py
cmdb/importer/importer_object.py
cmdb/interface/rest_api/importer_routes/importer_object_routes.py

Changes:
* MDS Objects can now be imported in JSON format

DAT-864 import mds objects json

---

app/src/app/framework/render/fields/special/ref.component.ts
app/src/app/framework/render/sections/multi-data-section/multi-data-section.component.ts
app/src/app/framework/services/object.service.ts
cmdb/interface/rest_api/framework_routes/objects_routes.py

Changes:
* Summaryline for mds ref fields

summaryline for mds

---

app/src/app/framework/object/components/object-references/object-references-by-type/object-references-by-type.component.ts
app/src/app/framework/object/components/object-references/object-references-type-column/object-references-type-column.component.html
app/src/app/framework/object/components/object-references/object-references-type-column/object-references-type-column.component.ts
app/src/app/framework/object/components/object-references/object-references.component.html
app/src/app/framework/object/components/object-references/object-references.component.ts
app/src/app/framework/object/modals/objects-delete-modal/objects-delete-modal.component.html
app/src/app/framework/object/object-edit/object-edit.component.html
app/src/app/framework/object/object-edit/object-edit.component.scss
app/src/app/framework/render/sections/multi-data-section/multi-data-section.component.html
app/src/app/framework/render/sections/multi-data-section/multi-data-section.component.ts
app/src/app/framework/type/builder/modals/preview-modal/preview-modal.component.html
app/src/app/framework/type/type-delete/type-delete.component.html
app/src/app/framework/type/type-delete/type-delete.component.scss
app/src/app/framework/type/type-delete/type-delete.component.ts
cmdb/framework/managers/object_manager.py
cmdb/interface/rest_api/framework_routes/objects_routes.py

Changes:
* Added MDS matches in "Referenced By" of object overview
* Improved MDS functionality
* Refactoring code

DAT-863 referenced-by-mds

---

app/src/app/framework/framework.component.html
app/src/app/framework/framework.component.ts
app/src/app/framework/framework.module.ts
app/src/app/framework/type/builder/controls/multi-section.control.ts
app/src/app/framework/type/builder/modals/diagnostic-modal/diagnostic-modal.component.html
app/src/app/framework/type/builder/modals/diagnostic-modal/diagnostic-modal.component.ts
app/src/app/framework/type/builder/modals/preview-modal/preview-modal.component.html
app/src/app/framework/type/components/clean-button/clean-button.component.html
app/src/app/framework/type/components/clean-button/clean-button.component.ts
app/src/app/framework/type/modals/cleanup-modal/cleanup-modal.component.html
app/src/app/framework/type/modals/cleanup-modal/cleanup-modal.component.ts
app/src/app/layout/components/block/block.component.html
app/src/app/layout/components/block/block.component.ts
app/src/app/layout/components/charts/charts.component.html
app/src/app/layout/components/content-header/content-header.component.html
app/src/app/layout/components/content-header/content-header.component.ts
cmdb/framework/managers/object_manager.py
cmdb/interface/docs/static/index.html
docs/source/dev_guide/fixtures/database_config.csv
docs/source/dev_guide/repository.rst
docs/source/dev_guide/setup.rst

Changes:
* Refactoring of UI
* Improved references workflow when an object is referenced by a section and a multi data section to not display the object twice

DAT-858-improve-unclean-functionality

---

cmdb/updater/__init__.py
cmdb/updater/versions/updater_20240603.py

Changes:
* Updater for version 2.2.0 added

DAT-865-updater for 2.2.0

---

app/src/app/framework/object/object-copy/object-copy.component.html
app/src/app/framework/object/object-copy/object-copy.component.scss
app/src/app/framework/object/object-copy/object-copy.component.ts
app/src/app/framework/render/sections/multi-data-section/multi-data-section.component.html
app/src/app/framework/render/sections/multi-data-section/multi-data-section.component.ts
app/src/app/framework/type/builder/modals/preview-modal/preview-modal.component.html
app/src/app/framework/type/builder/modals/preview-modal/preview-modal.component.scss
cmdb/framework/managers/object_manager.py

Changes:
* MDS can be duplicated
* pagination for MDS table
* 'save' button changed to 'add' button
* Select Dropdown now inside popup
* KeyValue error fixed for MDS
* Required of fields is considered in popup

DAT-867 duplicate MDS

---

app/src/app/modules/docapi/services/docapi.service.ts
cmdb/interface/rest_api/framework_routes/objects_routes.py

Changes:
* Fixed docapi creation issue

DAT 868-docapi creation

---

Makefile
app/package-lock.json
app/package.json
contrib/deb/control

Changes:
* Preparation for building 2.2.0 packages

DAT-872-2.2.0-package-building

---

app/src/app/framework/render/sections/multi-data-section/multi-data-section.component.html
app/src/app/framework/render/sections/multi-data-section/multi-data-section.component.ts
app/src/app/framework/type/builder/modals/preview-modal/preview-modal.component.html
app/src/app/framework/type/builder/modals/preview-modal/preview-modal.component.ts

Changes:
* handling of texts for edit mds entry
* fixed pager indicator for mds table

DAT-876-mds-popups

---

app/src/app/framework/render/sections/multi-data-section/multi-data-section.component.ts

Changes:
* fixed dates not currectly changed in mds tables

DAT-885 date in mds table fix

---

docs/source/requirements.txt

DAT-886-sphinx-fix

---

cmdb/interface/rest_api/auth_routes.py

adapt users

---

cmdb/exporter/exporter_base.py
cmdb/interface/rest_api/user_management_routes/users_routes.py
cmdb/manager/manager_provider.py
cmdb/security/security.py

Changes:
* Added user creation

DAT-960 user creation

---

cmdb/interface/net_app/__init__.py
cmdb/interface/rest_api/__init__.py
cmdb/interface/rest_api/auth_routes.py
cmdb/interface/rest_api/connection.py
cmdb/interface/rest_api/framework_routes/object_links_routes.py
cmdb/interface/rest_api/system_routes/setup_routes.py

Changes:
* Object links can now only be created once for the same two IDs
* Added setup API endpoint
* small fixes

DAT-966 object links fix

---

cmdb/interface/rest_api/media_library_routes/media_file_route_utils.py
cmdb/interface/rest_api/media_library_routes/media_file_routes.py
cmdb/media_library/media_file_manager.py

Changes:
* Fixed fast clicking delete crash on uploaded files

DAT-983 deleting files

---

.github/workflows/continous-integration.yml
cmdb/templates/template_data.py

Changes:
* Updated github actions

DAT-986 update github actions

---

cmdb/__init__.py
cmdb/__main__.py
cmdb/__setup__.py
cmdb/database/utils.py
cmdb/interface/rest_api/auth_routes.py
cmdb/interface/rest_api/system_routes/setup_routes.py
cmdb/interface/rest_api/user_management_routes/users_routes.py
cmdb/interface/route_utils.py
cmdb/security/key/holder.py
cmdb/utils/helpers.py
cmdb/utils/logger.py
contrib/docker/compose/backend/Dockerfile
etc/test_users.json

Changes:
* DOckerfile for backend build
* Test file for cloud users
* small fixes and refactoring

DAT-987-build for backend

---

cmdb/interface/rest_api/user_management_routes/rights_routes.py
cmdb/interface/route_utils.py
cmdb/manager/base_manager.py
cmdb/manager/categories_manager.py
cmdb/manager/docapi_templates_manager.py
cmdb/manager/groups_manager.py
cmdb/manager/locations_manager.py
cmdb/manager/object_links_manager.py
cmdb/manager/objects_manager.py
cmdb/manager/rights_manager.py
cmdb/search/searchers.py
cmdb/user_management/__init__.py
tests/fixtures/fixture_management.py

Changes:
* Refactored RightManager
* Refactored CategoriesManager
* Removed several dependencies

DAT-1026-refactor right manager

---

cmdb/errors/manager/media_file_manager/__init__.py
cmdb/errors/manager/media_file_manager/media_file_manager_errors.py
cmdb/framework/datagerry_assistant/profile_assistant.py
cmdb/interface/rest_api/framework_routes/categories_routes.py
cmdb/interface/rest_api/media_library_routes/media_file_route_utils.py
cmdb/interface/rest_api/media_library_routes/media_file_routes.py
cmdb/interface/rest_api/user_management_routes/user_settings_routes.py
cmdb/manager/categories_manager.py
cmdb/manager/manager_provider.py
cmdb/manager/media_files_manager.py
cmdb/manager/section_templates_manager.py
cmdb/manager/users_settings_manager.py

Changes:
* Refactored CategoriesManager
* Refactored MediaFilesManager
* Refactored UsersSettingsManager

DAT-1027 refactor media file manager

---

cmdb/database/mongo_database_manager.py
cmdb/database/utils.py
cmdb/errors/manager/types_manager/__init__.py
cmdb/errors/manager/types_manager/types_manager_errors.py
cmdb/framework/cmdb_render.py
cmdb/framework/models/category.py
cmdb/framework/models/link.py
cmdb/framework/models/type_model/type_field_section.py
cmdb/framework/models/type_model/type_reference_section.py
cmdb/framework/models/type_model/type_render_meta.py
cmdb/importer/importer_object.py
cmdb/interface/rest_api/importer_routes/importer_object_routes.py
cmdb/interface/rest_api/setting_routes.py
cmdb/manager/base_manager.py
cmdb/manager/objects_manager.py
cmdb/manager/types_manager.py
cmdb/updater/updater.py

Changes:
* Fixed several cyclic imports
* Added specific errors for TypeManager

DAT-1040 cyclic imports

---

cmdb/errors/dg_assistant/__init__.py
cmdb/errors/dg_assistant/dg_assistant_errors.py
cmdb/framework/datagerry_assistant/profile_assistant.py
cmdb/framework/datagerry_assistant/profile_type_constructor.py
cmdb/framework/models/category.py
cmdb/interface/rest_api/exporter_routes/exporter_object_routes.py
cmdb/interface/rest_api/special_routes.py
cmdb/user_management/models/settings.py
cmdb/utils/helpers.py

DAT-972-import-error

---

cmdb/database/utils.py
cmdb/framework/models/category_model/category_tree.py
cmdb/interface/__init__.py
cmdb/interface/api_pagination.py
cmdb/interface/response.py
cmdb/interface/rest_api/docapi_routes.py
cmdb/interface/rest_api/exportd_routes/exportd_job_routes.py
cmdb/interface/rest_api/exportd_routes/exportd_log_routes.py
cmdb/interface/rest_api/framework_routes/categories_routes.py
cmdb/interface/rest_api/framework_routes/location_routes.py
cmdb/interface/rest_api/framework_routes/object_links_routes.py
cmdb/interface/rest_api/framework_routes/objects_routes.py
cmdb/interface/rest_api/framework_routes/section_template_routes.py
cmdb/interface/rest_api/framework_routes/types_routes.py
cmdb/interface/rest_api/import_routes.py
cmdb/interface/rest_api/logs_routes.py
cmdb/interface/rest_api/media_library_routes/media_file_routes.py
cmdb/interface/rest_api/settings_routes/date_routes.py
cmdb/interface/rest_api/user_management_routes/groups_routes.py
cmdb/interface/rest_api/user_management_routes/rights_routes.py
cmdb/interface/rest_api/user_management_routes/user_settings_routes.py
cmdb/interface/rest_api/user_management_routes/users_routes.py
cmdb/interface/route_utils.py
cmdb/utils/helpers.py

Changes:
* Refactored response messages
* default hook improvement

DAT-1052-refactor-response-messages

---

cmdb/interface/rest_api/routes/auth_routes.py
cmdb/interface/route_utils.py

DAT-1080 login issue

---

app/src/app/modules/main/main-routing.module.ts
app/src/app/reporting/category/components/category-add-modal/category-add-modal.component.html
app/src/app/reporting/category/components/category-add-modal/category-add-modal.component.ts
app/src/app/reporting/category/components/category-form/category-form.component.html
app/src/app/reporting/category/components/category-form/category-form.component.ts
app/src/app/reporting/category/components/category-overview/category-overview.component.html
app/src/app/reporting/category/components/category-overview/category-overview.component.ts
app/src/app/reporting/category/report-category-routing.module.ts
app/src/app/reporting/category/report-category.module.ts
app/src/app/reporting/report/components/report-overview/report-overview.component.ts
app/src/app/reporting/report/report-routing.module.ts
app/src/app/reporting/report/report.module.ts
app/src/app/reporting/reporting-routing.module.ts
app/src/app/reporting/reporting.module.ts
app/src/app/reporting/services/report-category.service.ts

Also Added the whole structure for the reporting system

Reports Category Page

---

app/src/app/reporting/category/components/category-add-modal/category-add-modal.component.html
app/src/app/reporting/category/components/category-add-modal/category-add-modal.component.ts
app/src/app/reporting/category/components/category-overview/category-overview.component.html
app/src/app/reporting/category/components/category-overview/category-overview.component.ts

- Added modal to add a new category
- comment out the functions

Created New Report Category Modal

---

cmdb/__setup__.py
cmdb/__update__.py
cmdb/database/mongo_query_builder.py
cmdb/database/utils.py
cmdb/exporter/writer/writer_base.py
cmdb/framework/constants.py
cmdb/interface/rest_api/responses/__init__.py
cmdb/interface/rest_api/responses/get_list_response.py
cmdb/interface/rest_api/responses/get_multi_response.py
cmdb/interface/rest_api/responses/get_single_response.py
cmdb/interface/rest_api/responses/gridfs_response.py
cmdb/interface/rest_api/responses/helpers/api_projection.py
cmdb/interface/rest_api/responses/helpers/api_projector.py
cmdb/interface/rest_api/routes/report_routes/report_category_routes.py
cmdb/interface/rest_api/routes/report_routes/report_routes.py
cmdb/manager/media_files_manager.py
cmdb/models/reports_model/cmdb_report.py
cmdb/security/auth/auth_module.py
cmdb/security/auth/base_authentication_provider.py
cmdb/security/auth/base_provider_config.py
cmdb/security/auth/providers/ldap_auth_config.py
cmdb/security/auth/providers/ldap_auth_provider.py
cmdb/security/auth/providers/local_auth_config.py
cmdb/security/auth/providers/local_auth_provider.py

Changes:
* Added MongoDBQueryBuilder

DAT-1106 mongodb query builder

---

cmdb/interface/rest_api/routes/report_routes/report_routes.py

Changes:
* create report/update report improved

DAT-1115-improve-report-routes

---

cmdb/interface/rest_api/init_rest_api.py
cmdb/interface/rest_api/routes/report_routes/report_routes.py
cmdb/interface/rest_api/routes/webhook_routes/webhook_routes.py
cmdb/manager/reports_manager.py
cmdb/manager/webhooks_manager.py

Changes:
* Added webhooks API routes
* Added webhooks manager

DAT-1128 webhook api routes

---

cmdb/framework/constants.py
cmdb/manager/manager_provider_model/manager_provider.py
cmdb/manager/manager_provider_model/manager_type_enum.py
cmdb/manager/report_categories_manager.py
cmdb/manager/webhooks_event_manager.py
cmdb/manager/webhooks_manager.py

Changes:
* Added webhooks event manager

DAT-1129-webhooks event manager

---

app/src/app/reporting/report/components/create-report/create-report.component.html
app/src/app/reporting/report/components/create-report/create-report.component.ts

- Added Multi-Value Dropdown to Create Report Page
- Also Added a back button
- Changed the style of save button

Added Multi-Value Dropdown to Create Report Page

---

cmdb/interface/rest_api/routes/system_routes/setup_routes.py
cmdb/interface/route_utils.py

DAT-1131 subscription routes

---

cmdb/database/mongo_database_manager.py
cmdb/interface/rest_api/routes/framework_routes/objects_routes.py
cmdb/manager/base_manager.py

Changes:
* Fixed cleaning type where fields are removed

DAT-1139-types-clean

---

cmdb/database/mongo_query_builder.py
cmdb/interface/rest_api/routes/framework_routes/objects_routes.py
cmdb/interface/rest_api/routes/report_routes/report_category_routes.py
cmdb/interface/rest_api/routes/report_routes/report_routes.py
cmdb/models/reports_model/cmdb_report.py

Changes:
* Update reports when type fields are removed

DAT-1140-update-reports-after-type-change

---

cmdb/database/mongo_query_builder.py
cmdb/framework/datagerry_assistant/profile_assistant.py
cmdb/interface/rest_api/routes/framework_routes/objects_routes.py
cmdb/interface/rest_api/routes/framework_routes/special_routes.py
cmdb/interface/rest_api/routes/report_routes/report_routes.py
cmdb/models/type_model/type.py

Changes:
* MDS fields for reports
* Fixed assistant route

DAT-1148-mds-fields-in-reports

---

cmdb/database/mongo_database_manager.py
cmdb/database/mongo_query_builder.py
cmdb/framework/constants.py
cmdb/interface/rest_api/init_rest_api.py
cmdb/interface/rest_api/routes/framework_routes/objects_routes.py
cmdb/interface/rest_api/routes/framework_routes/types_routes.py
cmdb/interface/rest_api/routes/report_routes/report_routes.py
cmdb/interface/rest_api/routes/webhook_routes/webhook_event_routes.py
cmdb/interface/rest_api/routes/webhook_routes/webhook_routes.py
cmdb/manager/base_manager.py
cmdb/manager/objects_manager.py
cmdb/manager/webhooks_manager.py
cmdb/models/webhook_model/cmdb_webhook_event_model.py
cmdb/updater/versions/updater_20200512.py

Changes:
* Creation of webhook events
* webhook event routes added
* Small fixes
* Handling of numeric fields in reports

DAT-1167 events for webhooks

---

cmdb/models/right_model/all_rights.py
cmdb/models/right_model/framework_rights.py

Changes:
* Added rights for Webhooks

DAT-1168 Webhook permissions

---

cmdb/database/mongo_query_builder.py
cmdb/errors/mongo_query_builder/__init__.py
cmdb/errors/mongo_query_builder/mongo_query_builder_errors.py

Changes:
* Error handling query builder

DAT-1177 query builder exceptions

---

cmdb/interface/rest_api/routes/framework_routes/location_routes.py
cmdb/interface/rest_api/routes/framework_routes/section_template_routes.py

Changes:
* Fixed location creation bug

DAT-1179 location creation bug

---

cmdb/database/mongo_query_builder.py
cmdb/security/acl/access_control_list_section.py
cmdb/security/acl/access_control_section_dict.py
cmdb/security/acl/control.py
cmdb/security/acl/group_acl.py
tests/functional/framework/test_functional_objects.py
tests/functional/framework/test_functional_types.py
tests/unit/framework/test_unit_bulk_change_objects.py

Changes:
* refactored ACL classes
* It is possible now to create reports without conditions

DAT-1180 reports without conditions

---

cmdb/__init__.py
cmdb/__main__.py
cmdb/interface/cmdb_app.py
cmdb/interface/rest_api/routes/system_routes/setup_routes.py
cmdb/interface/route_utils.py
cmdb/models/user_model/user.py
etc/test_users.json

Changes:
* added api_level and config_items_limit to user model
* Added local mode to startup parameters
* improved subscription routes

DAT-1189 adapt user model

---

cmdb/interface/blueprints/api_blueprint.py
cmdb/interface/rest_api/api_level_enum.py
cmdb/interface/rest_api/auth_method_enum.py
cmdb/interface/rest_api/routes/auth_routes.py
cmdb/interface/rest_api/routes/framework_routes/objects_routes.py
cmdb/interface/rest_api/routes/system_routes/setup_routes.py
cmdb/interface/rest_api/routes/user_management_routes/users_routes.py
cmdb/interface/route_utils.py

Changes:
* Added API Levels
* Added subscription user update route

DAT-1190 api levels

---

CHANGELOG.md
tests/conftest.py
tests/fixtures/fixture_management.py
tests/functional/framework/test_functional_objects.py

Changes:
* Added changelog for release 2.1.0
* Added changelog for release 2.2.0

changelog updated

---

cmdb/interface/rest_api/init_rest_api.py
cmdb/interface/rest_api/routes/framework_routes/objects_routes.py
cmdb/interface/rest_api/routes/framework_routes/types_routes.py
cmdb/interface/route_utils.py
tests/functional/framework/test_functional_types.py
tests/unit/framework/test_unit_bulk_change_objects.py

Changes:
* Fixed type tests
* Added config item limit for objects

DAT-1197 type tests

---

cmdb/framework/importer/importers/object_importer.py
cmdb/interface/rest_api/routes/framework_routes/objects_routes.py
requirements.txt

Changes:
* Config item limit for importing objects

DAT-1203-ci-object-import

---

cmdb/interface/route_utils.py

Changes:
* Adapted validation for super users

DAT-1221-login-service-portal

---

cmdb/framework/importer/importers/object_importer.py
cmdb/interface/rest_api/routes/framework_routes/objects_routes.py
cmdb/interface/route_utils.py

Changes:
* Config item sync to service portal

DAT-1224-config-item-sync

---

cmdb/interface/rest_api/routes/framework_routes/types_routes.py
cmdb/interface/rest_api/routes/report_routes/report_routes.py
cmdb/manager/reports_manager.py

Changes:
* Types are not deletable if there are objects or reports using it

DAT-1219 deleting types reports

---

cmdb/interface/blueprints/api_blueprint.py
cmdb/interface/rest_api/routes/auth_routes.py
cmdb/interface/rest_api/routes/exporter_routes/exporter_object_routes.py
cmdb/interface/rest_api/routes/exporter_routes/exporter_type_routes.py
cmdb/interface/rest_api/routes/framework_routes/categories_routes.py
cmdb/interface/rest_api/routes/framework_routes/docapi_routes.py
cmdb/interface/rest_api/routes/framework_routes/location_routes.py
cmdb/interface/rest_api/routes/framework_routes/logs_routes.py
cmdb/interface/rest_api/routes/framework_routes/object_links_routes.py
cmdb/interface/rest_api/routes/framework_routes/objects_routes.py
cmdb/interface/rest_api/routes/framework_routes/search_routes.py
cmdb/interface/rest_api/routes/framework_routes/section_template_routes.py
cmdb/interface/rest_api/routes/framework_routes/setting_routes.py
cmdb/interface/rest_api/routes/framework_routes/special_routes.py
cmdb/interface/rest_api/routes/framework_routes/types_routes.py
cmdb/interface/rest_api/routes/importer_routes/importer_object_routes.py
cmdb/interface/rest_api/routes/importer_routes/importer_type_routes.py
cmdb/interface/rest_api/routes/media_library_routes/media_file_routes.py
cmdb/interface/rest_api/routes/settings_routes/date_routes.py
cmdb/interface/rest_api/routes/settings_routes/system_routes.py
cmdb/interface/rest_api/routes/user_management_routes/groups_routes.py
cmdb/interface/rest_api/routes/user_management_routes/rights_routes.py
cmdb/interface/rest_api/routes/user_management_routes/users_routes.py
cmdb/interface/route_utils.py

DAT-1234 refactor API functions

---

cmdb/database/mongo_database_manager.py
cmdb/interface/rest_api/routes/framework_routes/objects_routes.py
cmdb/manager/webhooks_manager.py

Changes:
* Fixed clean with reports

DAT-1239-clean-with-reports

---

cmdb/manager/security_manager.py
cmdb/security/key/holder.py

DAT-1241-activated keys

---

cmdb/manager/security_manager.py
cmdb/security/key/holder.py

Changes:
* Debug symmetric key

DAT-1242-symmetric-key-debug

---

app/src/app/framework/services/object.service.ts
cmdb/interface/rest_api/routes/framework_routes/objects_routes.py
cmdb/interface/route_utils.py
cmdb/manager/security_manager.py
cmdb/models/object_model/cmdb_object.py
cmdb/open_api/components/responses.yaml
cmdb/open_api/components/schemas/CmdbObject.yaml
cmdb/open_api/components/schemas/CollectionParameters.yaml
cmdb/open_api/components/schemas/MultiDataSection.yaml
cmdb/open_api/components/security.yaml
cmdb/open_api/openapi.yaml
cmdb/open_api/paths/objects/objects-by-id.yaml
cmdb/open_api/paths/objects/objects-many.yaml
cmdb/open_api/paths/objects/objects-state.yaml
cmdb/open_api/paths/objects/objects.yaml

Changes:
* Added openapi routes for objects

DAT-1243-openapi-object-routes

---

cmdb/interface/rest_api/routes/report_routes/report_routes.py
cmdb/open_api/components/schemas/CmdbCategory.yaml
cmdb/open_api/openapi.yaml
cmdb/open_api/paths/categories/categories-by-id.yaml
cmdb/open_api/paths/categories/categories.yaml
cmdb/open_api/paths/objects/objects.yaml

Changes:
* Added openapi documentation for category routes

DAT-1256 openapi category routes

---

app/src/app/framework/services/type.service.ts
cmdb/interface/rest_api/routes/framework_routes/types_routes.py
cmdb/open_api/components/schemas/CmdbType.yaml
cmdb/open_api/components/schemas/CmdbTypeField.yaml
cmdb/open_api/components/schemas/CmdbTypeRenderMeta.yaml
cmdb/open_api/openapi.yaml
cmdb/open_api/paths/objects/objects.yaml
cmdb/open_api/paths/types/types-by-id.yaml
cmdb/open_api/paths/types/types-counts.yaml
cmdb/open_api/paths/types/types.yaml

Changes:
* Added openapi routes for types

DAT-1257 openapi type routes

---

.pylintrc
cmdb/interface/rest_api/routes/framework_routes/section_template_routes.py
cmdb/open_api/components/schemas/CmdbSectionTemplate.yaml
cmdb/open_api/openapi.yaml
cmdb/open_api/paths/section_templates/section-templates-by-id.yaml
cmdb/open_api/paths/section_templates/section-templates.yaml

Changes:
* Added section template routes in openapi

DAT-1258-openapi-section-template-routes

---

cmdb/interface/rest_api/routes/user_management_routes/users_routes.py
cmdb/open_api/components/schemas/CmdbUser.yaml
cmdb/open_api/openapi.yaml
cmdb/open_api/paths/users/users-by-id.yaml
cmdb/open_api/paths/users/users.yaml

Changes:
* Added openapi routes for users

DAT-1262-openapi-routes-users

---

cmdb/models/object_model/cmdb_object.py
cmdb/open_api/components/schemas/CmdbCategory.yaml
cmdb/open_api/components/schemas/CmdbObject.yaml
cmdb/open_api/components/schemas/CmdbSectionTemplate.yaml
cmdb/open_api/components/schemas/CmdbType.yaml
cmdb/open_api/components/schemas/CmdbTypeField.yaml
cmdb/open_api/components/schemas/CmdbTypeRenderMeta.yaml
cmdb/open_api/components/schemas/CmdbUser.yaml
cmdb/open_api/components/schemas/CollectionParameters.yaml
cmdb/open_api/components/schemas/MultiDataSection.yaml
cmdb/open_api/components/security.yaml
cmdb/open_api/openapi.yaml
cmdb/open_api/paths/categories/categories-by-id.yaml
cmdb/open_api/paths/categories/categories.yaml
cmdb/open_api/paths/objects/objects-by-id.yaml
cmdb/open_api/paths/objects/objects-state.yaml
cmdb/open_api/paths/objects/objects.yaml
cmdb/open_api/paths/section_templates/section-templates-by-id.yaml
cmdb/open_api/paths/section_templates/section-templates.yaml
cmdb/open_api/paths/types/types-by-id.yaml
cmdb/open_api/paths/types/types.yaml
cmdb/open_api/paths/users/users-by-id.yaml
cmdb/open_api/paths/users/users.yaml

Changes:
* OpenAPI schema documentation

DAT-1263 openapi schema documentation

---

cmdb/errors/manager/categories_manager/categories_manager_errors.py
cmdb/errors/manager/relations_manager/__init__.py
cmdb/errors/manager/relations_manager/relations_manager_errors.py
cmdb/manager/__init__.py
cmdb/manager/categories_manager.py
cmdb/manager/manager_provider_model/manager_provider.py
cmdb/manager/manager_provider_model/manager_type_enum.py
cmdb/manager/relations_manager.py
cmdb/manager/types_manager.py
cmdb/models/relation_model/__init__.py

Changes:
* Added RelationsManager
* Added RelationsManager specific errors

DAT-1293-implement-relations-manager

---

.pylintrc
cmdb/class_schema/cmdb_category_schema.py
cmdb/class_schema/cmdb_type_schema.py
cmdb/errors/models/cmdb_user/__init__.py
cmdb/errors/models/cmdb_user/cmdb_user_errors.py
cmdb/interface/blueprints/api_blueprint.py
cmdb/interface/rest_api/responses/login_response.py
cmdb/interface/rest_api/routes/auth_routes.py
cmdb/interface/rest_api/routes/user_management_routes/users_routes.py
cmdb/interface/route_utils.py
cmdb/manager/users_manager.py
cmdb/models/user_model/cmdb_user.py
cmdb/open_api/paths/users/users-by-id.yaml
cmdb/security/auth/providers/ldap_auth_provider.py
cmdb/security/auth/providers/local_auth_provider.py

Changes:
* Object specific CmdbRelations
* Improved CmdbUser API Routes

DAT-1341-object-specific-relations

---

.pylintrc
cmdb/class_schema/cmdb_category_schema.py
cmdb/class_schema/cmdb_object_relation_schema.py
cmdb/class_schema/cmdb_relation_schema.py
cmdb/class_schema/cmdb_type_schema.py
cmdb/class_schema/cmdb_user_schema.py
cmdb/database/mongo_connector.py
cmdb/database/mongo_database_manager.py
cmdb/errors/manager/object_relation_logs_manager/__init__.py
cmdb/errors/manager/object_relation_logs_manager/object_relation_logs_manager_errors.py
cmdb/interface/rest_api/routes/exporter_routes/exporter_object_routes.py
cmdb/interface/rest_api/routes/exporter_routes/exporter_type_routes.py
cmdb/interface/rest_api/routes/framework_routes/objects_routes.py
cmdb/interface/rest_api/routes/log_routes/object_relation_logs_routes.py
cmdb/interface/rest_api/routes/relation_routes/object_relation_routes.py
cmdb/manager/groups_manager.py
cmdb/manager/object_relation_logs_manager.py
cmdb/models/group_model/cmdb_user_group.py
cmdb/models/log_model/__init__.py
tests/functional/framework/test_functional_objects.py
tests/unit/framework/test_unit_bulk_change_objects.py

Changes:
* Added creation of ObjectRelationLogs in workflows

DAT-1344 object relation logs

---

cmdb/framework/rendering/cmdb_render.py
cmdb/interface/rest_api/routes/framework_routes/objects_routes.py
cmdb/interface/rest_api/routes/relation_routes/object_relation_routes.py

Changes:
* Fixed object creation
* Added relation_id check for object relations

DAT-1371 fix object creation

---

cmdb/errors/manager/report_categories_manager/__init__.py
cmdb/errors/manager/report_categories_manager/report_categories_manager_errors.py
cmdb/errors/models/cmdb_report_category/__init__.py
cmdb/errors/models/cmdb_report_category/cmdb_report_category_errors.py
cmdb/interface/rest_api/routes/relation_routes/relations_routes.py
cmdb/interface/rest_api/routes/report_routes/report_category_routes.py
cmdb/manager/report_categories_manager.py
cmdb/models/reports_model/cmdb_report_category.py

Changes:
* Improved ReportCategory Routes

DAT-1373-improve-report-category-routes

---

cmdb/errors/models/isms_impact/__init__.py
cmdb/errors/models/isms_impact/isms_impact_errors.py
cmdb/framework/constants.py
cmdb/manager/__init__.py
cmdb/manager/isms_manager/impact_manager.py
cmdb/manager/manager_provider_model/manager_provider.py
cmdb/manager/manager_provider_model/manager_type_enum.py
cmdb/models/isms_model/isms_impact.py
cmdb/models/isms_model/isms_risk_class.py

DAT-1360-isms-impact

---

cmdb/errors/manager/impact_manager/__init__.py
cmdb/errors/manager/impact_manager/impact_manager_errors.py
cmdb/interface/rest_api/init_rest_api.py
cmdb/interface/rest_api/responses/insert_single_response.py
cmdb/interface/rest_api/routes/isms_routes/__init__.py
cmdb/interface/rest_api/routes/isms_routes/impact_routes.py
cmdb/manager/isms_manager/impact_manager.py
cmdb/manager/query_builder/base_query_builder.py
cmdb/manager/query_builder/builder.py
cmdb/manager/query_builder/builder_parameters.py
cmdb/manager/query_builder/pipeline_builder.py
cmdb/manager/query_builder/quick_search_pipeline_builder.py
cmdb/manager/query_builder/search_pipeline_builder.py
cmdb/manager/query_builder/search_references_pipeline_builder.py
cmdb/manager/users_settings_manager.py
cmdb/models/cmdb_versioning.py
cmdb/models/isms_model/isms_impact.py
cmdb/models/isms_model/isms_likelihood.py
cmdb/models/log_model/log_action_enum.py
cmdb/models/right_model/all_rights.py
cmdb/models/right_model/isms_rights.py

Changes:
* Added impact API routes
* Improved documentation

DAT-1361 isms-impact-routes

---

cmdb/errors/manager/protection_goal_manager/__init__.py
cmdb/errors/manager/protection_goal_manager/protection_goal_manager_errors.py
cmdb/errors/models/isms_protection_goal/__init__.py
cmdb/errors/models/isms_protection_goal/isms_protection_goal_errors.py
cmdb/framework/constants.py
cmdb/interface/rest_api/init_rest_api.py
cmdb/interface/rest_api/routes/isms_routes/impact_routes.py
cmdb/interface/rest_api/routes/isms_routes/likelihood_routes.py
cmdb/interface/rest_api/routes/isms_routes/protection_goal_routes.py
cmdb/interface/rest_api/routes/webhook_routes/webhook_event_routes.py
cmdb/interface/rest_api/routes/webhook_routes/webhook_routes.py
cmdb/interface/route_utils.py
cmdb/manager/__init__.py
cmdb/manager/isms_manager/impact_manager.py
cmdb/manager/isms_manager/likelihood_manager.py
cmdb/manager/isms_manager/protection_goal_manager.py
cmdb/manager/manager_provider_model/manager_provider.py
cmdb/manager/manager_provider_model/manager_type_enum.py
cmdb/models/isms_model/__init__.py
cmdb/models/isms_model/isms_data.py
cmdb/models/isms_model/isms_protection_goal.py
cmdb/models/right_model/all_rights.py
cmdb/models/right_model/base_right.py
cmdb/models/right_model/export_rights.py
cmdb/models/right_model/isms_rights.py
cmdb/models/right_model/levels_enum.py
cmdb/models/right_model/system_rights.py

Changes:
* Added ISMS Protection Goal routes
* Improved documentation

DAT-1364-isms-protection-goals

---

cmdb/framework/importer/messages/import_message.py
cmdb/framework/importer/messages/import_success_message.py
cmdb/interface/rest_api/routes/isms_routes/impact_routes.py
cmdb/interface/rest_api/routes/isms_routes/likelihood_routes.py
cmdb/models/isms_model/isms_likelihood.py
cmdb/security/acl/builder.py
cmdb/security/acl/permission.py
cmdb/security/auth/auth_settings.py

Changes:
* Calc basis is unique for likelihood and impacts

DAT-1388-unique-calc-basis

---

app/src/app/toolbox/isms/configure/steps/impact/impact.component.html
app/src/app/toolbox/isms/configure/steps/impact/impact.component.scss
app/src/app/toolbox/isms/configure/steps/impact/impact.component.ts
app/src/app/toolbox/isms/configure/steps/impact/modal/impact-modal.component.html
app/src/app/toolbox/isms/configure/steps/impact/modal/impact-modal.component.scss
app/src/app/toolbox/isms/configure/steps/impact/modal/impact-modal.component.ts
app/src/app/toolbox/isms/configure/steps/likelihood/likelihood.component.html
app/src/app/toolbox/isms/configure/steps/likelihood/likelihood.component.ts
app/src/app/toolbox/isms/configure/steps/likelihood/modal/likelihood-modal.component.ts
app/src/app/toolbox/isms/isms.module.ts
app/src/app/toolbox/isms/models/impact.model.ts
app/src/app/toolbox/isms/models/isms-config.model.ts
app/src/app/toolbox/isms/services/impact.service.ts
app/src/app/toolbox/isms/utils/isms-utils.ts

-Implemented Impact UI
-minor improvements

Impact Ui Implemented

---

app/src/app/framework/object/object-view/object-view.component.ts
app/src/app/toolbox/isms/configure/steps/impact-categories/impact-categories.component.html
app/src/app/toolbox/isms/configure/steps/impact-categories/impact-categories.component.scss
app/src/app/toolbox/isms/configure/steps/impact-categories/impact-categories.component.ts
app/src/app/toolbox/isms/configure/steps/impact-categories/modal/impact-category-modal.component.html
app/src/app/toolbox/isms/configure/steps/impact-categories/modal/impact-category-modal.component.scss
app/src/app/toolbox/isms/configure/steps/impact-categories/modal/impact-category-modal.component.ts
app/src/app/toolbox/isms/configure/steps/impact/impact.component.html
app/src/app/toolbox/isms/configure/steps/impact/impact.component.scss
app/src/app/toolbox/isms/configure/steps/impact/modal/impact-modal.component.ts
app/src/app/toolbox/isms/configure/steps/likelihood/likelihood.component.html
app/src/app/toolbox/isms/configure/steps/likelihood/likelihood.component.scss
app/src/app/toolbox/isms/configure/steps/likelihood/modal/likelihood-modal.component.ts
app/src/app/toolbox/isms/configure/steps/risk-classes/risk-classes.component.html
app/src/app/toolbox/isms/configure/steps/risk-classes/risk-classes.component.scss
app/src/app/toolbox/isms/models/impact-category.model.ts
app/src/app/toolbox/isms/services/impact-category.service.ts
app/src/scss/_icon.scss

- Impact categories UI Implemented
- Minor Icon style Improvements

Feature - Dat 1378 - UI for impact categories

---

app/src/app/toolbox/isms/configure/steps/protection-goals/modal/protection-goal-modal.component.html
app/src/app/toolbox/isms/configure/steps/protection-goals/modal/protection-goal-modal.component.ts
app/src/app/toolbox/isms/configure/steps/protection-goals/protection-goals.component.html
app/src/app/toolbox/isms/configure/steps/protection-goals/protection-goals.component.scss
app/src/app/toolbox/isms/configure/steps/protection-goals/protection-goals.component.ts
app/src/app/toolbox/isms/isms.module.ts
app/src/app/toolbox/isms/models/protection-goal.model.ts
app/src/app/toolbox/isms/services/protection-goal.service.ts

- Implemented UI for Protection goal
- It's modal also added

UI for protection goal added

---

cmdb/errors/exporter/__init__.py
cmdb/errors/exporter/exporter_errors.py
cmdb/errors/importer/__init__.py
cmdb/errors/manager/extendable_options_manager/__init__.py
cmdb/errors/manager/extendable_options_manager/extendable_options_manager_errors.py
cmdb/framework/exporter/format/base_exporter_format.py
cmdb/framework/exporter/format/csv_export_format.py
cmdb/framework/exporter/format/json_export_format.py
cmdb/framework/exporter/format/xlsx_export_format.py
cmdb/framework/exporter/format/xml_export_format.py
cmdb/framework/importer/configs/base_importer_config.py
cmdb/interface/rest_api/init_rest_api.py
cmdb/interface/rest_api/routes/framework_routes/__init__.py
cmdb/interface/rest_api/routes/framework_routes/extendable_option_routes.py
cmdb/interface/rest_api/routes/isms_routes/impact_category_routes.py
cmdb/interface/rest_api/routes/isms_routes/risk_class_routes.py
cmdb/manager/__init__.py
cmdb/manager/extendable_options_manager.py
cmdb/manager/manager_provider_model/manager_provider.py
cmdb/manager/manager_provider_model/manager_type_enum.py
cmdb/models/right_model/all_rights.py
cmdb/models/right_model/framework_rights.py

Changes:
* Extendable Options API Routes
* Improved documentation

DAT-1431-extendable-options-api

---

cmdb/errors/manager/object_groups_manager/__init__.py
cmdb/errors/manager/object_groups_manager/object_groups_manager_errors.py
cmdb/errors/manager/risk_manager/__init__.py
cmdb/errors/manager/risk_manager/risk_manager_errors.py
cmdb/interface/rest_api/auth_method_enum.py
cmdb/interface/rest_api/init_rest_api.py
cmdb/interface/rest_api/responses/__init__.py
cmdb/interface/rest_api/responses/delete_single_response.py
cmdb/interface/rest_api/responses/get_list_response.py
cmdb/interface/rest_api/responses/get_single_response.py
cmdb/interface/rest_api/responses/gridfs_response.py
cmdb/interface/rest_api/responses/helpers/api_pagination.py
cmdb/interface/rest_api/routes/framework_routes/extendable_option_routes.py
cmdb/interface/rest_api/routes/framework_routes/object_groups_routes.py
cmdb/interface/rest_api/routes/isms_routes/__init__.py
cmdb/interface/rest_api/routes/isms_routes/risk_routes.py
cmdb/manager/__init__.py
cmdb/manager/generic_manager.py
cmdb/manager/isms_manager/risk_manager.py
cmdb/manager/manager_provider_model/manager_provider.py
cmdb/manager/manager_provider_model/manager_type_enum.py
cmdb/manager/objects_manager.py
cmdb/models/extendable_option_model/cmdb_extendable_option.py
cmdb/models/isms_model/isms_threat.py
cmdb/models/isms_model/isms_vulnerability.py
cmdb/models/isms_model/risk_type_enum.py
cmdb/models/right_model/all_rights.py
cmdb/models/right_model/isms_rights.py

Changes:
* Added ISMSRisk workflows to backend
* Improved ExtendableOptions logics
* Improved Backend documentation

DAT-1392-isms-risk-api-routes

---

cmdb/__main__.py
cmdb/interface/rest_api/routes/framework_routes/extendable_option_routes.py
cmdb/interface/rest_api/routes/framework_routes/object_groups_routes.py
cmdb/interface/rest_api/routes/isms_routes/control_meassure_routes.py
cmdb/interface/rest_api/routes/isms_routes/impact_category_routes.py
cmdb/interface/rest_api/routes/isms_routes/impact_routes.py
cmdb/interface/rest_api/routes/isms_routes/isms_config_routes.py
cmdb/interface/rest_api/routes/isms_routes/likelihood_routes.py
cmdb/interface/rest_api/routes/isms_routes/protection_goal_routes.py
cmdb/interface/rest_api/routes/isms_routes/risk_class_routes.py
cmdb/interface/rest_api/routes/isms_routes/risk_matrix_routes.py
cmdb/interface/rest_api/routes/isms_routes/risk_routes.py
cmdb/interface/rest_api/routes/isms_routes/threat_routes.py
cmdb/interface/rest_api/routes/isms_routes/vulnerability_routes.py
cmdb/interface/rest_api/routes/settings_routes/system_routes.py
cmdb/manager/generic_manager.py
cmdb/models/isms_model/isms_helper/isms_risk_matrix_helper.py
cmdb/utils/system_config_reader.py

Changes:
* Fixed manager errors

DAT-1499-collection-validator

---

app/src/app/toolbox/isms/models/risk.model.ts
app/src/app/toolbox/isms/services/risk.service.ts

- Risk Service Added
- Risk Model Added

Risk service added

---

cmdb/errors/manager/persons_manager/__init__.py
cmdb/errors/manager/persons_manager/persons_manager_errors.py
cmdb/errors/models/cmdb_person/__init__.py
cmdb/errors/models/cmdb_person/cmdb_person_errors.py
cmdb/framework/constants.py
cmdb/interface/rest_api/init_rest_api.py
cmdb/interface/rest_api/routes/system_routes/setup_routes.py
cmdb/interface/rest_api/routes/user_management_routes/persons_routes.py
cmdb/manager/__init__.py
cmdb/manager/manager_provider_model/manager_provider.py
cmdb/manager/manager_provider_model/manager_type_enum.py
cmdb/manager/persons_manager.py
cmdb/models/isms_model/isms_helper/isms_risk_matrix_helper.py
cmdb/models/isms_model/isms_protection_goal.py
cmdb/models/person_model/__init__.py
cmdb/models/person_model/cmdb_person.py
cmdb/models/right_model/all_rights.py
cmdb/models/right_model/user_management_rights.py
tests/functional/framework/test_functional_objects.py
tests/functional/framework/test_functional_types.py
tests/functional/management/test_functional_user.py
tests/unit/framework/test_unit_bulk_change_objects.py

Changes:
* Added CmdbPerson workflows to the backend
* Improved Backend documentation

DAT-1517-cmdb-person-workflows

---

cmdb/errors/manager/person_groups_manager/__init__.py
cmdb/errors/manager/person_groups_manager/person_groups_manager_errors.py
cmdb/errors/models/cmdb_person_group/__init__.py
cmdb/errors/models/cmdb_person_group/cmdb_person_group_errors.py
cmdb/interface/rest_api/routes/user_management_routes/person_groups_routes.py
cmdb/interface/rest_api/routes/user_management_routes/persons_routes.py
cmdb/manager/__init__.py
cmdb/manager/manager_provider_model/manager_provider.py
cmdb/manager/manager_provider_model/manager_type_enum.py
cmdb/manager/person_groups_manager.py
cmdb/models/person_group_model/__init__.py
cmdb/models/person_group_model/cmdb_person_group.py
cmdb/models/right_model/all_rights.py
cmdb/models/right_model/user_management_rights.py
cmdb/models/user_management_constants.py
cmdb/security/auth/auth_settings.py
cmdb/security/auth/providers/local_auth_config.py
cmdb/security/auth/providers/local_auth_provider.py
cmdb/security/key/generator.py
cmdb/security/key/holder.py
cmdb/security/token/generator.py
tests/functional/framework/test_functional_objects.py

Changes:
* PersonGroup workflows added to backend
* Improved backend documentation

Feature/dat 1522/ person group class

---

cmdb/errors/models/cmdb_extendable_option/cmdb_extendable_option_errors.py
cmdb/framework/importer/configs/object_importer_config.py
cmdb/framework/importer/importers/object_importer.py
cmdb/framework/media_library/media_file_metadata.py
cmdb/interface/rest_api/routes/media_library_routes/media_file_routes.py
cmdb/manager/logs_manager.py
cmdb/models/isms_model/isms_control_meassure.py
cmdb/models/isms_model/isms_impact.py
cmdb/models/isms_model/isms_impact_category.py
cmdb/models/isms_model/isms_likelihood.py
cmdb/models/isms_model/isms_risk.py
cmdb/models/isms_model/isms_risk_class.py
cmdb/models/isms_model/isms_risk_matrix.py
cmdb/models/isms_model/isms_threat.py
cmdb/models/isms_model/isms_vulnerability.py
cmdb/models/location_model/cmdb_location.py
cmdb/models/log_model/cmdb_object_log.py
cmdb/models/object_group_model/cmdb_object_group.py
cmdb/models/relation_model/cmdb_relation.py
cmdb/models/reports_model/cmdb_report.py
cmdb/models/webhook_model/cmdb_webhook_event.py
cmdb/models/webhook_model/cmdb_webhook_model.py
cmdb/models/webhook_model/webhook_event_type_enum.py
cmdb/security/auth/base_authentication_provider.py
cmdb/security/auth/base_provider_config.py
cmdb/security/auth/providers/ldap_auth_config.py
cmdb/security/auth/providers/ldap_auth_provider.py

Changes:
* Small fixes backend
* Improved backend documentation

DAT-1529-small-fixes

---

cmdb/framework/search/search_param.py
cmdb/framework/search/search_result.py
cmdb/interface/blueprints/root_blueprint.py
cmdb/interface/rest_api/routes/user_management_routes/person_groups_routes.py
cmdb/interface/rest_api/routes/user_management_routes/persons_routes.py
cmdb/models/isms_model/isms_risk_assessment.py
cmdb/models/person_group_model/cmdb_person_group.py
cmdb/models/person_model/cmdb_person.py

Changes:
* Added CmdbPerson workflows
* Added CmdbPersonGroup workflows
* improved backend documentation

DAT-1530-person-workflows

---

cmdb/errors/manager/control_meassure_assignment_manager/__init__.py
cmdb/errors/manager/control_meassure_assignment_manager/control_meassure_assignment_manager_errors.py
cmdb/errors/models/isms_control_meassure_assignment/__init__.py
cmdb/errors/models/isms_control_meassure_assignment/isms_control_meassure_assignment_errors.py
cmdb/framework/constants.py
cmdb/interface/rest_api/init_rest_api.py
cmdb/interface/rest_api/routes/exporter_routes/exporter_object_routes.py
cmdb/interface/rest_api/routes/framework_routes/section_template_routes.py
cmdb/interface/rest_api/routes/isms_routes/__init__.py
cmdb/interface/rest_api/routes/isms_routes/meassure_control_assignment_routes.py
cmdb/manager/__init__.py
cmdb/manager/isms_manager/control_meassure_assignment_manager.py
cmdb/manager/manager_provider_model/manager_provider.py
cmdb/manager/manager_provider_model/manager_type_enum.py
cmdb/manager/security_manager.py
cmdb/models/isms_model/__init__.py
cmdb/models/isms_model/isms_control_meassure_assignment.py
cmdb/models/right_model/all_rights.py
cmdb/models/right_model/isms_rights.py
cmdb/security/acl/builder.py

Changes:
* Added workflows for ControlMeassure Assignments in the backend
* improved Backend documentation

DAT-1442-control-meassure-assignment-workflow

---

cmdb/interface/rest_api/init_rest_api.py
cmdb/interface/rest_api/routes/importer_routes/importer_isms_routes.py
cmdb/models/isms_model/__init__.py
cmdb/models/isms_model/isms_import_type_enum.py

Changes:
* Added ISMS importer routes

DAT-1451-isms-importer-routes

---

cmdb/errors/manager/protection_goal_manager/__init__.py
cmdb/errors/manager/protection_goal_manager/protection_goal_manager_errors.py
cmdb/errors/manager/threat_manager/__init__.py
cmdb/errors/manager/threat_manager/threat_manager_errors.py
cmdb/errors/manager/vulnerability_manager/__init__.py
cmdb/errors/manager/vulnerability_manager/vulnerability_manager_errors.py
cmdb/interface/rest_api/routes/isms_routes/protection_goal_routes.py
cmdb/interface/rest_api/routes/isms_routes/risk_assessment_routes.py
cmdb/interface/rest_api/routes/isms_routes/threat_routes.py
cmdb/interface/rest_api/routes/isms_routes/vulnerability_routes.py
cmdb/manager/base_manager.py
cmdb/manager/isms_manager/protection_goal_manager.py
cmdb/manager/isms_manager/risk_assessment_manager.py
cmdb/manager/isms_manager/threat_manager.py
cmdb/manager/isms_manager/vulnerability_manager.py
cmdb/manager/media_files_manager.py
cmdb/manager/rights_manager.py
cmdb/models/log_model/cmdb_log.py
cmdb/models/right_model/base_right.py

Changes:
* Improved backend documentation
* Risk assessment followup logics
* ProtectionGoal followup logics
* Threat followup logics
* Vulnerability followup logics

DAT-1584-improve-delete-risk-assessment

---

cmdb/database/mongo_database_manager.py
cmdb/interface/rest_api/routes/importer_routes/importer_object_routes.py
cmdb/interface/rest_api/routes/isms_routes/likelihood_routes.py
cmdb/manager/isms_manager/likelihood_manager.py
cmdb/manager/webhooks_manager.py
cmdb/models/log_model/cmdb_object_log.py
cmdb/models/webhook_model/cmdb_webhook_event.py
cmdb/models/webhook_model/cmdb_webhook_model.py
cmdb/security/acl/access_control_list.py
cmdb/security/acl/access_control_list_section.py

Changes:
* Likelihood workflows when updated and deleted
* improved backend documentation

DAT-1587-likelihood-workflows

---

cmdb/errors/manager/report_categories_manager/__init__.py
cmdb/errors/models/cmdb_report/__init__.py
cmdb/errors/models/cmdb_report/cmdb_report_errors.py
cmdb/interface/rest_api/routes/framework_routes/docapi_routes.py
cmdb/interface/rest_api/routes/framework_routes/object_groups_routes.py
cmdb/interface/rest_api/routes/report_routes/report_category_routes.py
cmdb/interface/route_utils.py
cmdb/manager/isms_manager/protection_goal_manager.py
cmdb/manager/object_groups_manager.py
cmdb/manager/report_categories_manager.py
cmdb/models/reports_model/cmdb_report.py

Changes:
* Added ObjectGroups workflows
* Improved ReportCategories workflows
* Improved Backend documentation

DAT-1596-object-group-workflows

---

cmdb/class_schema/isms_risk_assessment_schema.py
cmdb/database/database_services/collection_validator.py
cmdb/database/database_services/updater_helpers.py
cmdb/database/mongo_connector.py
cmdb/database/mongo_database_manager.py
cmdb/database/updater/base_database_update.py
cmdb/errors/manager/reports_manager/__init__.py
cmdb/errors/manager/reports_manager/reports_manager_errors.py
cmdb/framework/importer/importers/object_importer.py
cmdb/interface/blueprints/api_blueprint.py
cmdb/interface/gunicorn.py
cmdb/interface/http_server.py
cmdb/interface/rest_api/init_rest_api.py
cmdb/interface/rest_api/routes/auth_routes.py
cmdb/interface/rest_api/routes/framework_routes/objects_routes.py
cmdb/interface/rest_api/routes/framework_routes/types_routes.py
cmdb/interface/rest_api/routes/report_routes/report_routes.py
cmdb/interface/route_utils.py
cmdb/manager/base_manager.py
cmdb/manager/object_groups_manager.py
cmdb/manager/objects_manager.py
cmdb/manager/reports_manager.py

Changes:
* Updater adaptions
* Added upsert functionality
* improved CmdbReport workflows
* Improved Backend documentation

DAT-1599-update-routine

---

cmdb/framework/rendering/cmdb_render.py
cmdb/interface/rest_api/init_rest_api.py
cmdb/interface/rest_api/routes/framework_routes/types_routes.py
cmdb/interface/rest_api/routes/isms_routes/__init__.py
cmdb/interface/rest_api/routes/isms_routes/isms_report_routes.py
cmdb/models/isms_model/__init__.py
cmdb/models/isms_model/isms_report_builder.py
cmdb/models/right_model/all_rights.py
cmdb/models/right_model/isms_rights.py

Changes:
* Preparations for ISMS Report - Report Matrix

DAT-1577-report-matrix

---

cmdb/framework/rendering/cmdb_render.py
cmdb/models/isms_model/isms_control_measure.py
cmdb/models/isms_model/isms_control_measure_assignment.py

Changes:
* Bgugfixes render cloud

DAT-1617 cloud bugfixing

---

cmdb/database/database_utils.py
cmdb/database/mongo_connector.py
cmdb/database/mongo_database_manager.py
cmdb/interface/rest_api/routes/framework_routes/objects_routes.py

Changes:
* Retry logics preparation
* New API route for CmdbObject count

DAT-1618 retry logics preparation

---

cmdb/database/mongo_database_manager.py
cmdb/framework/rendering/cmdb_render.py
cmdb/interface/rest_api/routes/framework_routes/extendable_option_routes.py
cmdb/interface/rest_api/routes/framework_routes/location_routes.py
cmdb/interface/rest_api/routes/importer_routes/importer_object_routes.py
cmdb/interface/rest_api/routes/isms_routes/isms_config_routes.py
cmdb/interface/rest_api/routes/isms_routes/isms_report_routes.py
cmdb/models/isms_model/isms_report_builder.py
cmdb/models/isms_model/isms_risk.py
cmdb/models/isms_model/isms_threat.py
cmdb/models/isms_model/isms_vulnerability.py

Changes:
* Added risk treatment plan
* Several bugfixes

DAT-1578-report-risk-treatment-plan

---

cmdb/framework/rendering/cmdb_render.py
cmdb/interface/rest_api/routes/importer_routes/importer_isms_routes.py
cmdb/interface/rest_api/routes/isms_routes/isms_report_routes.py
cmdb/interface/rest_api/routes/isms_routes/risk_class_routes.py
cmdb/interface/rest_api/routes/isms_routes/risk_routes.py
cmdb/manager/isms_manager/risk_manager.py
cmdb/manager/isms_manager/threat_manager.py

Changes:
* Backend bugfixes
* Improved backend documentation
* Added ISMS Risk Treatment Report preparation

DAT-1636-testing-isms

---

cmdb/interface/blueprints/api_blueprint.py
cmdb/interface/rest_api/responses/response_parameters/api_parameters.py
cmdb/interface/rest_api/responses/response_parameters/collection_parameters.py
cmdb/interface/rest_api/responses/response_parameters/group_parameters.py
cmdb/interface/rest_api/responses/response_parameters/type_parameters.py
cmdb/interface/rest_api/routes/importer_routes/importer_isms_routes.py

DAT-1636-importer-fixes

---

cmdb/class_schema/isms_risk_assessment_schema.py
cmdb/errors/manager/objects_manager/objects_manager_errors.py
cmdb/interface/rest_api/routes/framework_routes/objects_routes.py
cmdb/interface/rest_api/routes/isms_routes/isms_report_routes.py
cmdb/interface/rest_api/routes/isms_routes/risk_assessment_routes.py
cmdb/manager/objects_manager.py

Changes:
* Improved SOA report

DAT-1638-isms-report-improvements

---

cmdb/database/database_utils.py
cmdb/database/mongo_connector.py
cmdb/database/mongo_database_manager.py
cmdb/interface/rest_api/routes/isms_routes/risk_assessment_routes.py
requirements.txt

DAT-1645-cloud-issues

---

cmdb/interface/rest_api/routes/isms_routes/risk_assessment_routes.py

Changes:
* RiskAssessment update route improved

DAT-1649-risk-assessment-improvements

---

cmdb/interface/rest_api/routes/isms_routes/isms_report_routes.py
cmdb/interface/rest_api/routes/isms_routes/risk_assessment_routes.py

Changes:
* ISMS Report - Risk treatment plan

DAT-1651 risk treatment plan report

---

cmdb/interface/blueprints/api_blueprint.py
cmdb/interface/rest_api/routes/isms_routes/impact_routes.py
cmdb/interface/rest_api/routes/isms_routes/isms_report_routes.py
cmdb/interface/rest_api/routes/isms_routes/likelihood_routes.py
cmdb/interface/rest_api/routes/isms_routes/risk_assessment_routes.py

Changes:
* Improved ISMS Risk Assessment Report
* Improved Risk Assessment Update functionality

DAT-1652-risk-assessment-report

---

cmdb/class_schema/isms_risk_assessment_schema.py
cmdb/interface/rest_api/routes/isms_routes/isms_report_routes.py

Changes:
* Added impact categories to risk assessment report

DAT-1654 risk assessements report

---

cmdb/interface/rest_api/routes/ci_explorer_routes/ci_explorer_routes.py

Changes:
* Removed duplicate nodes from CI Explorer

DAT-1817-remove-duplicate-nodes

---

cmdb/interface/docs/static/_sources/sources/changelog.rst.txt
cmdb/interface/docs/static/index.html
cmdb/interface/docs/static/sources/changelog.html
docs/source/sources/changelog.rst

Changes:
* Added changelogs to documentation

added changelogs

---

.gitignore
cmdb/interface/dispatcher_middleware.py
cmdb/interface/rest_api/ai_models/__init__.py
cmdb/interface/rest_api/ai_models/gemini_model.py
cmdb/interface/rest_api/init_rest_api.py
cmdb/interface/rest_api/routes/ai_routes/type_assistant_routes.py
cmdb/interface/rest_api/routes/ci_explorer_routes/ci_explorer_routes.py
cmdb/interface/rest_api/routes/framework_routes/logs_routes.py
requirements.txt

Changes:
* Integration of AI for PoC
* Filters for CI Explorer routes added

DAT-1810-ai-integration

---

cmdb/interface/rest_api/routes/isms_routes/threat_routes.py
cmdb/interface/rest_api/routes/isms_routes/vulnerability_routes.py
cmdb/interface/rest_api/routes/user_management_routes/person_groups_routes.py
cmdb/interface/rest_api/routes/user_management_routes/persons_routes.py
cmdb/interface/rest_api/routes/user_management_routes/users_routes.py
cmdb/models/isms_model/isms_vulnerability.py
cmdb/models/person_model/cmdb_person.py
cmdb/open_api/components/schemas/CmdbPerson.yaml
cmdb/open_api/components/schemas/CmdbPersonGroup.yaml
cmdb/open_api/components/schemas/CmdbType.yaml
cmdb/open_api/components/schemas/isms/IsmsThreat.yaml
cmdb/open_api/components/schemas/isms/IsmsVulnerability.yaml
cmdb/open_api/openapi.yaml
cmdb/open_api/paths/isms/threats/threats-by-id.yaml
cmdb/open_api/paths/isms/threats/threats.yaml
cmdb/open_api/paths/isms/vulnerabilities/vulnerabilities-by-id.yaml
cmdb/open_api/paths/isms/vulnerabilities/vulnerabilities.yaml
cmdb/open_api/paths/person_groups/person-groups-by-id.yaml
cmdb/open_api/paths/person_groups/person-groups.yaml
cmdb/open_api/paths/persons/persons-by-id.yaml
cmdb/open_api/paths/persons/persons.yaml
cmdb/open_api/paths/users/users-by-id.yaml
cmdb/open_api/paths/users/users-password.yaml
cmdb/open_api/paths/users/users.yaml

Changes:
* API routes documentation

api routes documentation

---

cmdb/interface/rest_api/routes/ai_routes/__init__.py
cmdb/interface/rest_api/routes/ai_routes/type_assistant_routes.py

Changes:
* AI API route improvement

DAT-1870-ai-route-improvement

---

cmdb/interface/rest_api/routes/ai_routes/type_assistant_routes.py

Changes:
* Added first version of prompt

DAT-1872-prompt preparation

---

requirements.txt

Changes:
* Python version 3.10 introduced

DAT-1875 python upgrade to 3.10

---

.github/workflows/continous-integration.yml
requirements.txt

Changes:
* bumped pymongo to 4.13.2
* bumped github actions to test against python 3.12

DAT-1938 bump pymongo

---

cmdb/database/mongo_database_manager.py
cmdb/errors/database/__init__.py
cmdb/errors/database/database_errors.py
cmdb/interface/rest_api/routes/framework_routes/objects_routes.py
cmdb/interface/route_utils.py

Changes:
* initial Database error handling

DAT-1953-initial-setup

---

cmdb/interface/rest_api/routes/ai_routes/type_assistant_routes.py

Changes:
* Added json formatting response
* Added type validation

DAT-1959-json-format

---

app/src/app/framework/section_templates/layout/modals/section-template-clone/section-template-clone-modal.component.html
app/src/app/framework/section_templates/layout/modals/section-template-clone/section-template-clone-modal.component.scss

Updated **clone modal styling** with consistent effects and form styling.

section template modal UI improved

---

cmdb/interface/rest_api/routes/ai_routes/type_assistant_routes.py

Changes:
* Improved promt
* Improved response handling

improved prompt

---

app/src/app/modules/auth/login/login.component.ts
app/src/app/modules/connect/connect-routing.module.ts

Restricted Connect page in cloud mode

Bugfix/dat 1973/restrict connect page

---

cmdb/class_schema/cmdb_category_schema.py
cmdb/database/mongo_connector.py
cmdb/database/mongo_database_manager.py
cmdb/interface/gunicorn_config.py
cmdb/interface/rest_api/routes/framework_routes/objects_routes.py
cmdb/process_management/cmdb_process.py

Changes:
* idle connection to db handling

DAT-1974-db-idle-connection

---

Makefile
cmdb/database/database_utils.py
cmdb/database/mongo_database_manager.py
cmdb/database/mongo_query_builder.py
cmdb/framework/results/iteration_result.py
cmdb/interface/rest_api/routes/connection.py
cmdb/interface/rest_api/routes/framework_routes/objects_routes.py
cmdb/manager/base_manager.py
cmdb/manager/generic_manager.py
cmdb/manager/objects_manager.py
cmdb/models/object_model/cmdb_object.py
cmdb/models/reports_model/cmdb_report.py
cmdb/models/type_model/cmdb_type.py

DAT-1983-unclean-action

---

app/src/app/toolbox/isms/person/person-list/person-list.component.ts
app/src/app/toolbox/isms/person/person-routing.module.ts

Breadcrumbs and link of persons been fixed

Bugfix/dat 1984/improve link and breadcrumbs of persons component

---

app/src/app/toolbox/isms/risks/risks-add/risks-add.component.ts

Fixed the issue where app incorrectly redirects to the Add Risk page instead of returning to the risk view.

Wrong navigation fixed

---

cmdb/class_schema/cmdb_user_schema.py
cmdb/database/database_services/collection_validator.py
cmdb/database/mongo_database_manager.py
cmdb/errors/manager/cached_user_manager/__init__.py
cmdb/errors/manager/cached_user_manager/cached_user_manager_errors.py
cmdb/errors/models/cmdb_cached_user/__init__.py
cmdb/errors/models/cmdb_cached_user/cmdb_cached_user_errors.py
cmdb/interface/rest_api/responses/login_response.py
cmdb/interface/rest_api/routes/auth_routes.py
cmdb/interface/rest_api/routes/framework_routes/types_routes.py
cmdb/interface/route_utils.py
cmdb/manager/__init__.py
cmdb/manager/base_manager.py
cmdb/manager/isms_manager/impact_manager.py
cmdb/manager/manager_provider_model/manager_provider.py
cmdb/manager/manager_provider_model/manager_type_enum.py
cmdb/manager/system_manager/cached_user_manager.py
cmdb/models/cached_user_model/__init__.py
cmdb/models/cached_user_model/cmdb_cached_user.py
cmdb/models/cmdb_dao.py
cmdb/models/isms_model/isms_impact.py
cmdb/models/user_management_constants.py
cmdb/models/user_model/cmdb_user.py

Changes:
* improvements user cache

DAT-1966-api-user-validation

---

app/src/app/framework/render/sections/multi-data-section/multi-data-section.component.ts

- MDS fields wrong order bug improved

MDS Fields order improved

---

cmdb/errors/security/__init__.py
cmdb/errors/security/security_errors.py
cmdb/interface/route_utils.py
cmdb/manager/security_manager.py
cmdb/manager/system_manager/cached_user_manager.py
cmdb/manager/system_manager/settings_manager.py
cmdb/security/auth/base_authentication_provider.py
cmdb/security/auth/providers/local_auth_provider.py

Changes:
* added api-key-handling

DAT-1991-key-routine

---

app/src/app/framework/render/fields/text/password.component.ts

Improved the generation of secured password

improve the generation of secure password

---

cmdb/framework/rendering/cmdb_render.py

Changes:
* all object relations displayed in object table

itsa-all-object-relations

---

cmdb/interface/rest_api/init_rest_api.py
cmdb/interface/rest_api/routes/itsa_api_routes/itsa_routes.py

itsa-sort-filter

---

cmdb/interface/rest_api/routes/itsa_api_routes/itsa_routes.py

Changes:
* Relation-sort in object table

itsa-rel-sort

---

cmdb/manager/open_celium_managers/__init__.py
cmdb/manager/open_celium_managers/open_celium_manager.py
cmdb/manager/system_manager/system_config_reader.py
cmdb/open_celium/__init__.py
cmdb/open_celium/oc_connector.py
etc/cmdb.conf

Changes:
* improved cmdb.conf for OC
* Inital OC connector created

DAT-2080-improve-conf

---

cmdb/interface/rest_api/routes/system_routes/setup_routes.py
cmdb/interface/route_utils.py
cmdb/manager/system_manager/cached_user_manager.py

Changes:
* Cache Users for Cloud

DAT-2091-user-cache-tests

---

cmdb/errors/open_celium/__init__.py
cmdb/errors/open_celium/connector/__init__.py
cmdb/errors/open_celium/connector/oc_connector_errors.py
cmdb/errors/open_celium/invoker/__init__.py
cmdb/errors/open_celium/invoker/oc_invoker_errors.py
cmdb/errors/open_celium/open_celium_errors.py
cmdb/interface/rest_api/init_rest_api.py
cmdb/interface/rest_api/routes/open_celium_routes/__init__.py
cmdb/interface/rest_api/routes/open_celium_routes/oc_connector_routes.py
cmdb/interface/rest_api/routes/open_celium_routes/oc_invoker_routes.py
cmdb/interface/route_utils.py
cmdb/manager/__init__.py
cmdb/manager/open_celium_managers/oc_connector_manager.py
cmdb/manager/open_celium_managers/oc_invoker_manager.py
cmdb/open_celium/oc_api_connector.py
etc/cmdb.conf

Changes:
* OC auth workflow
* OC GET invokers
* OC GET connectors
* OC POST connector
* OC errors wrapper
* initial OC error classes

DAT-2092-oc-auth-workflow

---

cmdb/errors/open_celium/__init__.py
cmdb/errors/open_celium/invoker/__init__.py
cmdb/errors/open_celium/template/__init__.py
cmdb/errors/open_celium/template/oc_template_errors.py
cmdb/interface/rest_api/init_rest_api.py
cmdb/interface/rest_api/routes/open_celium_routes/__init__.py
cmdb/interface/rest_api/routes/open_celium_routes/oc_connector_routes.py
cmdb/interface/rest_api/routes/open_celium_routes/oc_template_routes.py
cmdb/manager/__init__.py
cmdb/manager/open_celium_managers/oc_base_manager.py
cmdb/manager/open_celium_managers/oc_connection_manager.py
cmdb/manager/open_celium_managers/oc_connector_manager.py
cmdb/manager/open_celium_managers/oc_template_manager.py
cmdb/open_celium/oc_api_connector.py

Changes:
* Added template routes
* Added base manager

DAT-2014-get-automation

---

cmdb/interface/rest_api/routes/open_celium_routes/oc_invoker_routes.py
cmdb/manager/open_celium_managers/oc_connector_manager.py
cmdb/manager/open_celium_managers/oc_invoker_manager.py
cmdb/manager/open_celium_managers/oc_template_manager.py

Changes:
* get invoker by name API route added

DAT-2016 get invoker by name

---

cmdb/interface/rest_api/routes/system_routes/setup_routes.py
cmdb/manager/system_manager/cached_user_manager.py

Changes:
* deleting multiple cached users

delete multiple cached users

---

cmdb/interface/rest_api/routes/open_celium_routes/oc_connection_routes.py
cmdb/interface/rest_api/routes/open_celium_routes/oc_connector_routes.py
cmdb/interface/rest_api/routes/open_celium_routes/oc_invoker_routes.py
cmdb/manager/open_celium_managers/oc_invoker_manager.py
cmdb/models/right_model/all_rights.py
cmdb/models/right_model/oc_rights.py

Changes:
* Added get invokers flag
* Added connector rights

DAT-2120-invoker-flag
