app/package-lock.json, app/package.json
Dependabot cannot update to the required version.
**Remediation**
Upgrade node-forge to version 0.10.0 or later. For example:
```
"devDependencies": {
"node-forge": ">=0.10.0"
}
```
On the package-lock-json
**Solution:**
Update
```
"@angular-devkit/build-angular": "~0.803.27",
```
to
```
"@angular-devkit/build-angular": "^0.803.29",
```
On the package-json
=> [Dependabot] Fix CVE-2020-7720

app/src/app/search/search-result/search-result-bar/search-result-bar.component.html, app/src/app/search/search-result/search-result-bar/search-result-bar.component.ts, app/src/app/search/search.component.html, app/src/app/search/search.component.ts, cmdb/interface/rest_api/search_routes.py, cmdb/search/query/builder.py, cmdb/search/search_result.py, cmdb/search/searchers.py
A reference is now a content of a object in the search mode
[https://nethinks.atlassian.net/browse/NET-460](https://nethinks.atlassian.net/browse/NET-460)
Have a look at the following situation:
- object type “location“ is defined with a few fields like city, street, country, name
- object type “server“ is defined with a reference field to a location object
If a user will search for a location name (which is a field of a location object) in a current version of DATAGERRY, only the location will be found. The server object can not be found.
=> [NET-460] Follow search references

app/src/app/framework/type/type.component.ts
[NET-647 : Search in type list does not work](https://nethinks.atlassian.net/browse/NET-647)
- error From MongoDB: '$' by itself is not a valid Field Path
=> [NET-647] Search filter adapted for the type list.

app/src/app/dashboard/dashboard.component.ts, app/src/app/framework/models/cmdb-object.ts, app/src/app/framework/models/cmdb-render.ts, cmdb/framework/cmdb_object.py, cmdb/framework/cmdb_object_manager.py, cmdb/framework/cmdb_render.py
[NET-656](https://nethinks.atlassian.net/browse/NET-656) Dashboard: show latest editor in latest dashlet
Subtasks:
- [NET-806](https://nethinks.atlassian.net/browse/NET-806) cmdb object for last editor
- [NET-807](https://nethinks.atlassian.net/browse/NET-807) object render for last editor
- [NET-808](https://nethinks.atlassian.net/browse/NET-808) last editor in dashboard latest table
- [NET-809](https://nethinks.atlassian.net/browse/NET-809) user edit set in manager and rest routes
- [NET-810](https://nethinks.atlassian.net/browse/NET-810) ~~bulk user change editor~~
=> [NET-656] Last object editor

cmdb/framework/cmdb_render.py, cmdb/templates/template_data.py
[[NET-1060]](https://nethinks.atlassian.net/browse/NET-1060) CmdbRenderer adapted. Newly added reference section fields are assigned an empty value.
[NET-1060]: https://nethinks.atlassian.net/browse/NET-1060
=> [NET-1060] Crash after change type without cleanup

requirements.txt
- added dependency and bump of pyOpenSSL==23.2.0
=> [DAT-429] Bump cryptography to 41.0.1

cmdb/interface/rest_api/exporter_routes/export_object_routes.py, cmdb/interface/rest_api/exporter_routes/exporter_object_routes.py, requirements.txt
Bumped:
- openpyxl to 3.1.2
- lazy-object-proxy to 1.9.0
- packaging to 23.1
- fixed minor issues
=> [DAT-494] Bump openpyxl to 3.1.2

requirements.txt
Bumped:
- python-dateutil to 2.8.2
- pyasn1 to 0.5.0
- pytz to 2023.3
=> [DAT-497] Bump python-dateutil to 2.8.2

requirements.txt
Bumped:
- coverage to 7.2.7
- pycparser to 2.21
- pytest-html to 3.2.0
=> [DAT-500] Bumped pytest-html to 3.2.0

requirements.txt
Bumped:
- pytest-cov to 4.1.0
- snowballstemmer to 2.20.0
- xhtml2pdf to 0.2.11
=> [DAT-503] Bump xhtml2pdf to 0.2.11

requirements.txt
Bumped:
- pytest to 7.4.0
- pytest-metadata to 3.0.0
- toml to 0.10.2
=> [DAT-506] Bump pytest to 7.4.0

requirements.txt
Bumped:
- py to 1.11.0
- pycryptodome to 3.18.0
- pluggy to 1.2.0
=> [DAT-509] Bump pluggy to 1.2.0

requirements.txt
Bumped:
- Flask-Cors to 4.0.0
- attrs to 23.1.0
- Babel to 2.12.1
=> [DAT-512] Bump Flask-Cors to 4.0.0

requirements.txt
Bumped:
- pyPDF2 to 3.0.1
- reportlab to 3.6.13
- urllib3 to 2.0.3
=> [DAT-521] Bump urllib3 to 2.0.3

requirements.txt
Bumped:
- flake8 to 6.0.0
- pycodestyle to 2.10.0
- pyflakes to 3.0.1
- mccabe to 0.7.0
=> [DAT-528] Bump flake8 to 6.0.0

cmdb/__check__.py, cmdb/database/managers.py, cmdb/framework/cmdb_location.py
Features:
* Root location automatically created or fixed on startup
* Create counter for framework.locations if none is existent (before creating root location)
=> [DAT-539] Create Root Location automatically

app/src/app/layout/toast/toast-container/toast-container.component.ts
It wasn't working because when simpleFadeAnimation was triggering we had a "leave" transition.
=> Toast-Popup not closable when pressing the X in top right corner

app/src/app/framework/section_templates/layout/modals/section-template-delete/section-template-delete-modal.component.html, app/src/app/framework/section_templates/layout/modals/section-template-delete/section-template-delete-modal.component.ts, app/src/app/framework/section_templates/layout/section-template-builder/section-template-builder.component.html, app/src/app/framework/section_templates/layout/section-template-builder/section-template-builder.component.ts, app/src/app/framework/section_templates/section-template.component.html, app/src/app/framework/section_templates/section-template.component.ts, app/src/app/framework/section_templates/services/section-template.service.ts, app/src/app/framework/type/builder/builder.component.ts, app/src/app/framework/type/builder/configs/config.edit.ts, app/src/app/framework/type/builder/configs/section/section-field-edit.component.html, cmdb/framework/cmdb_section_template_manager.py, cmdb/interface/rest_api/framework_routes/section_template_routes.py, requirements.txt
Changes:
* Renamed "Name" to "Identifier" for sections
* Section Template Names can be edited
* Changes to global section templates are applied to types and objects (Add field, delete field, edit field)
* Delete popup for a global section template now cotains the number of affected types and objects
* Fixed some minor issues
=> DAT-671-editing-fields-for-global-sections

app/src/app/framework/object/modals/object-link-add-modal/object-link-add-modal.component.html
Fixed: Deactivate save button in object link creation when input is empty or invalid
=> Save button useable in object link creation

requirements.txt
Changes:
* Removed unused python packages from requirements.txt:
* attrs
* chardet
* py
* pyparsing
* PyPDF2
* pytz
* wrapt
* jdcal
* toml
=> DAT-732-remove-python-packages

requirements.txt
Bumped python packages
Changes:
* cryptography to 42.0.5
* pyOpenSSL to 24.1.0
* Authlib to 1.3.0
=> DAT-771 bump cryptography

app/src/app/framework/type/builder/builder.component.ts, app/src/app/framework/type/services/validation.service.ts
Fixed an issue where the button became disabled when changing the identifier before dropping a field. Now, the button functions correctly regardless of the order of these actions.
=> Fixed: Button Disabled When Changing Identifier Before Dropping Field

cmdb/interface/rest_api/routes/framework_routes/objects_routes.py, cmdb/interface/rest_api/routes/isms_routes/isms_report_routes.py, cmdb/interface/rest_api/routes/isms_routes/risk_assessment_routes.py, cmdb/manager/objects_manager.py
Changes:
* Added backend logics + route to duplicate a risk assessment
* removed type label from object summaries in ISMS reports
=> DAT-1661-duplicate-risk-assessments

requirements.txt
Changes:
* bumped flask to 3.1.1
* bumped werkzeug to 3.1.3
* bumped requests to 2.32.4
* bumped urllib3 to 2.5.0
* bumped pyOpenSSL to 25.1.0
* bumped cryptography to 45.0.5
=> DAT-1921 bump flask

app/src/app/settings/services/template-helper.service.ts
**toPromise()** is deprecated in RxJS 7. Update TemplateHelperService to use firstValueFrom instead for retrieving observables.
=> Fixed: Deprecated Class
